### ISSUE TITLE
quantile functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1036]
## Description

Add a function 

`real quantile(real[] x, real p)`

that returns the `p`-th quantile of `x`.  The sort functions can be used or the Boost accumulators to do it directly.  The value `p` should be tested that it's between 0 and 1 inclusive.

It could also be implemented for `vector` and `row_vector`.

This should come with a non-differentiability warning in the manual.

## Current Math Version
v2.18.0

**Comment by sakrejda** [comment]
@bob-carpenter : I believe we should add a detail to this issue so the next person doesn't make the same mistake as the first implementer.  My suggestion is: 

> Because this is a step function w.r.t. all arguments, when this function is instantiated with `var`/`fvar<T>` types it should still only return a `real` (explicitly drop the autodiff type and use only its value). 

I don't think there's a policy about whether to do this (or anything) with step functions in the math lib but maybe @syclik could comment on that part too?

**Comment by bob-carpenter** [comment]
Why did we want to cut the value here so there's no autodiff?  I know the whole function won't be continuous, but why not return the same type as the input?

For example, if I have `a = { b, c, d, e }` with `b < c < d < e` and I set `f = quantile(a, 0.75) * g`, should I not get the same result as `d * g`?  If we reduce the type and return a `double`, that won't be the case.   This will be tricky to doc one way or another.

I realize now I don't know how `quantile` is even supposed to be defined if say, we have 5 elements and ask for a 50% quantile or 3 elements and ask for a 25% quantile or something.  There must be general principles for this.  R at least must do something.  R seems to linearly interpolate:

```
> quantile(c(1,2,3,4), 0.5)
50% 
2.5 

> quantile(c(1,2,30,1000), 0.5)
50% 
 16 

> quantile(c(0, 1), 1/3)
33.33333% 
0.3333333 
```

**Comment by syclik** [comment]
@sakrejda: what should I be commenting on? I think we should just respect the autodiff types if it makes sense?

I'm with @bob-carpenter here... why should we make this a non-autodiff return type?

**Comment by sakrejda** [comment]
I said (above) autodiff doesn't make sense because this is always a step function with regards to all arguments so there's no sensible autodiff to be had (zero or NaN?), but I tagged you (@syclik) because I thought you could add some detail about what makes sense since this is marked as a "good first issue" but actually it's pretty complicated.  We could always implement a smoothed quantile function but I didn't think that's what this issue was about.

**Comment by bgoodri** [comment]
R has nine algorithms you can choose from by specifying the `type` argument
to the quantile function for dealing with things like ties and
intermediates.

**Comment by syclik** [comment]
> I said (above) autodiff doesn't make sense because this is always a step function with regards to all arguments so there's no sensible autodiff to be had (zero or NaN?), but I tagged you (@syclik) because I thought you could add some detail about what makes sense since this is marked as a "good first issue" but actually it's pretty complicated. We could always implement a smoothed quantile function but I didn't think that's what this issue was about.

@sakrejda: cool. Thanks for the context. 

What do you mean that the autodiff is a step function with regards to all arguments. Let's be a little clearer with an example:

```
real x[5] = {1, 2, 3, 4, 5};
real q1 = quantile(x, 0.25);
real q2 = quantile(x, 0.3);
```

In C++, it seems like we should return the scalar type of `x` here, either `double` or `stan::math::var`, depending on what `x` is?

What I don't understand is why it's discontinous (step function?). Shouldn't we see something like:
- `q1 = 2`, dq1 / dx[1] = 0, *dq1 / dx[2] = 1*, dq1 / dx[3:5] = 0?
- `q2 = 2.2` (or however we choose to interpolate; if it's linear...), dq2 / dx[1] = 0, *dq2 / dx[2] = 0.8*, *dq2 / dx[3] = 0.2*, dq2 / dx[4:5] = 0?

**Comment by bob-carpenter** [comment]
Ther'es not just the derivatives vs. x[1], ..., x[N] but also the derivatives vs. q in quantile({x[1], ..., x[N]}, q).

Aren't these both smooth if we interpolate and step functions if we take closest? Seems like an argument to interpolate.

**Comment by sakrejda** [comment]
I shouldn't have just said "step function", given: 

```
real p = ...
vector[N] x = {..., ..., ...}
real z = quantile(x, p)
```

Without interpolation: 
  - a continuous piecewise linear function in all values of `x`, these have discontinuous derivatives
  - a step function w.r.t. `p`, derivatives are either zero or NaN (might as well be NaN since the error is so big over the discontinuity that it will break HMC

With interpolation we can get whatever we want.

I would personally pick something that's continuous and smooth between min and max `x` for `p` and flat elsewhere because it would work with HMC for all parameters of the quantile function.  I think linear interpolation would still have discontinuous gradients so probably no reason to go with that unless there's a usage-specific reason (?)

**Comment by serenejiang** [comment]
Is this quantile function ready to use in Stan?

**Comment by mcol** [comment]
No, nothing has been implemented.

**Comment by roypabio** [comment]
This would be a really useful function. Do you have a sense when this might be ready?

**Comment by bbbales2** [comment]
Follow up question here, @adamhaber implemented a version of quantile over here based on R's default implementation: https://github.com/stan-dev/math/pull/2398#pullrequestreview-627558208

Yesterday reviewing it I thought leave autodiff off, the idea being we'd just implement:

```stan
real quantile(real[] xs, real p)
real[] quantile(real[] xs, real[] ps)

real quantile(vector xs, real p)
real[] quantile(vector xs, real[] ps)

real quantile(row_vector xs, real p)
real[] quantile(row_vector xs, real[] ps)
```

and call it a day. Reading the discussion here and looking at the functions we have, I'm more inclined to turn autodiff on, regardless of discontinuities. It's an easy switch to flip since everything is templated.

We currently allow functions like `min` or `max` on autodiff types and it would be more consistent with those functions to support autodiff. We're doing the default R implementation which uses interpolation, so the gradients aren't just zero.

Anyway it's not obvious to me what to do, so we'll just go ahead implementing this only for data types (so we're safe) and if it seems more consistent to turn on autodiff we can.
