### ISSUE TITLE
Add missing _rng functions

### ISSUE THREAD

**Issue by VMatthijs** [stan-dev/math#1040]
## Description
In an ideal world, the Stan Math library would have both a random number generator (an _rng file) and a density (a _log, _lpmf or _lpdf) implemented for all its distributions. This will be particularly important if we want to (try to) automate generation of synthetic data from the model.

Currently, according to my search through the math library, all distributions which have an RNG also have a density.  Conversely, however, the following distributions which have a density are missing a random number generator (`_rng` form of distribution):

```
./stan/math/prim/mat/prob/bernoulli_logit_glm
./stan/math/prim/mat/prob/gaussian_dlm_obs
./stan/math/prim/mat/prob/lkj_cov
./stan/math/prim/mat/prob/matrix_normal_prec
./stan/math/prim/mat/prob/multi_gp_cholesky
./stan/math/prim/mat/prob/multi_gp
./stan/math/prim/mat/prob/multi_normal_prec
./stan/math/prim/mat/prob/neg_binomial_2_log_glm
./stan/math/prim/mat/prob/normal_id_glm
./stan/math/prim/mat/prob/poisson_log_glm
./stan/math/prim/scal/prob/binomial_logit
./stan/math/prim/scal/prob/normal_sufficient
./stan/math/prim/scal/prob/std_normal
./stan/math/prim/scal/prob/wiener
```

## Example
For example, a first implementation of

`./stan/math/prim/mat/prob/bernoulli_logit_glm_rng_hpp`
(which is still missing the templating to allow for arguments that are scalars)

could do something like

```
#ifndef STAN_MATH_PRIM_MAT_PROB_BERNOULLI_LOGIT_GLM_RNG_HPP
#define STAN_MATH_PRIM_MAT_PROB_BERNOULLI_LOGIT_GLM_RNG_HPP

#include <stan/math/prim/scal/prob/bernoulli_logit_rng.hpp>
#include <stan/math/prim/scal/err/check_consistent_sizes.hpp>
#include <stan/math/prim/scal/err/check_consistent_size.hpp>
#include <stan/math/prim/scal/err/check_bounded.hpp>
#include <stan/math/prim/scal/err/check_finite.hpp>

namespace stan {
namespace math {
/**
 * Returns a draw from the Generalized Linear Model (GLM)
 * with Bernoulli distribution and logit link function.
 *
 * This is a convenience wrapper around
 * <code>bernoulli_logit_rng(alpha + x * beta, rng)</code>.
 *
 * @tparam RNG Type of pseudo-random number generator.
 * @param x design matrix
 * @param alpha intercept (in log odds)
 * @param beta weight vector
 * @param rng Pseudo-random number generator.
 * @return Bernoulli logit glm random variate
 * @throw std::domain_error if x, beta or alpha is infinite.
 * @throw std::invalid_argument if container sizes mismatch.
 */

template <class RNG>
inline std::vector<int>
           bernoulli_logit_glm_rng(const Eigen::Matrix<double, -1, -1> &x,
                                   const Eigen::Matrix<double, -1, 1> &alpha,
                                   const Eigen::Matrix<double, -1, 1> &beta,
                                   RNG& rng)

  const size_t N = x.col(0).size();
  const size_t M = x.row(0).size();

  check_bounded(function, "Vector of dependent variables", y, 0, 1);
  check_finite(function, "Weight vector", beta);
  check_finite(function, "Intercept", alpha);
  check_consistent_size(function, "Vector of dependent variables", y, N);
  check_consistent_size(function, "Weight vector", beta, M);
  if (is_vector<T_alpha>::value)
    check_consistent_sizes(function, "Vector of intercepts", alpha,
                           "Vector of dependent variables", y);
  Eigen::Matrix<double, -1, 1> theta = (x * beta) + alpha;
  check_finite(function, "Matrix of independent variables", theta);
  
  return bernoulli_logit_rng(theta, rng);
}
}  // namespace math
}  // namespace stan
#endif
```

## Expected Output
A solution to this issue would add the files

```
./stan/math/prim/mat/prob/bernoulli_logit_glm_rng.hpp
./stan/math/prim/mat/prob/gaussian_dlm_obs_rng.hpp
./stan/math/prim/mat/prob/lkj_cov_rng.hpp
./stan/math/prim/mat/prob/matrix_normal_prec_rng.hpp
./stan/math/prim/mat/prob/multi_gp_cholesky_rng.hpp
./stan/math/prim/mat/prob/multi_gp_rng.hpp
./stan/math/prim/mat/prob/multi_normal_prec_rng.hpp
./stan/math/prim/mat/prob/neg_binomial_2_log_glm_rng.hpp
./stan/math/prim/mat/prob/normal_id_glm_rng.hpp
./stan/math/prim/mat/prob/poisson_log_glm_rng.hpp
./stan/math/prim/scal/prob/binomial_logit_rng.hpp
./stan/math/prim/scal/prob/normal_sufficient_rng.hpp
./stan/math/prim/scal/prob/std_normal_rng.hpp
./stan/math/prim/scal/prob/wiener_rng.hpp
```

containing appropriate C++ code to generate draws from the distribution
whose density is given in the files

```
./stan/math/prim/mat/prob/bernoulli_logit_glm_log.hpp
./stan/math/prim/mat/prob/gaussian_dlm_obs_log.hpp
./stan/math/prim/mat/prob/lkj_cov_log.hpp
./stan/math/prim/mat/prob/matrix_normal_prec_log.hpp
./stan/math/prim/mat/prob/multi_gp_cholesky_log.hpp
./stan/math/prim/mat/prob/multi_gp_log.hpp
./stan/math/prim/mat/prob/multi_normal_prec_log.hpp
./stan/math/prim/mat/prob/neg_binomial_2_log_glm_log.hpp
./stan/math/prim/mat/prob/normal_id_glm_log.hpp
./stan/math/prim/mat/prob/poisson_log_glm_log.hpp
./stan/math/prim/scal/prob/binomial_logit_log.hpp
./stan/math/prim/scal/prob/normal_sufficient_log.hpp
./stan/math/prim/scal/prob/std_normal_log.hpp
./stan/math/prim/scal/prob/wiener_log.hpp
```

respectively.

## Current Math Version
v2.18.0

**Comment by peterwicksstringfield** [comment]
I have implementations and tests for four of the RNGs requested. But I would like a second perspective on a few things before preceding further.

The changes are here:
https://github.com/peterwicksstringfield/math/commit/adb72255083a25aa295d02a9a4c927f1f75458cd

I think I can turn that changeset into a pull-request somehow if that would make it easier to view. Not sure how.

Tests can be run like this:
runTests test/unit/math/prim/mat/prob/multi_normal_prec_test.cpp test/unit/math/prim/mat/prob/bernoulli_logit_glm_rng_test.cpp test/unit/math/prim/mat/prob/gaussian_dlm_obs_rng_test.cpp test/unit/math/prim/mat/prob/matrix_normal_prec_rng_test.cpp test/unit/math/prim/mat/err/check_pos_semidefinite_test.cpp

Some specific concerns:

1. In test/unit/math/prim/scal/prob/util.hpp we have utility functions for testing RNGs. By partitioning the range of the random variable into a set of bins, sampling from the RNG, counting samples in each bin, and comparing to expected counts with a chi-squared test. Previously, the bins were equi-probable. To test bernoulli_logit_glm_rng I extended the interface to allow for non-equi-probable bins. The names assert_matches_quantiles and assert_matches_cutpoints could use some work.

2. gaussian_dlm_obs_lpdf takes three covariance matrices as input (plus some other inputs) and allows 2 of them to be semi-definite rather than strictly definite. gaussian_dlm_obs_rng allows all 3 to be semi-definite. This seems harmless, and it made it easier to test.

3. The precision parameterized matrix_normal_prec_rng and multi_normal_prec_rng could use matrix inversion instead of backsolving if desired. I actually wrote it both ways and neither is much more complicated than the other.

4. I put the tests for multi_normal_prec_rng in multi_normal_prec_test.cpp with the lpdf tests, because that's how multi_normal_rng and multi_normal_lpdf do it. I'm not crazy about this organization.

5. I'm not 100% sure I understand the error behavior for Eigen::LDLT.

**Comment by peterwicksstringfield** [comment]
PR submitted. (What I did was I forked the stan/math repo and pushed my changes to a branch on the fork. github has no problem making a PR across forks.)

The automated testing process appears to have stopped with the clang auto format. At least you can see the code now though.

1. I've revised the naming of the chi-squared helpers.

2. Waiting for policy decision.

3. Cool.

4. I split the tests. Can revert that if needed easily.

5. No, I guess I don't have a specific question.

**Comment by bob-carpenter** [comment]
Thanks.  That all sounds good and I pinged @syclik about policy on semi-definiteness.  @bgoodri might weigh on on that one, too.

**Comment by syclik** [comment]
@peterwicksstringfield, thanks for the PR. I just needed a couple days to think about it. My preference is for the random number generators to match the probability distribution functions and the cumulative distribution functions. As far as I know, that's our current behavior across all of our lp{d,m}f / rngs now. (I'll just use rng and lpdf to to keep things short.)

There are two motivations for having the rngs match the lpdfs:
1. consistency. If that's what we're doing everywhere else, I think it makes sense to continue to do the same until a bump in major version.
2. parallelism across lpdf / cdf / rng code. I know it's not a guarantee, but if someone isn't as careful as you are to doc that the conditions are relaxed, then it'll be really easy for someone to be confused and change it so it matches (since that's what the rest of the code base does).

If you have a really good reason for allowing them to be different, I'd like to hear it. I know enough of this codebase where I value consistency a lot. I'm asked to drop into places I haven't been in years and when it doesn't behave similarly like other parts, it takes me quite a bit longer to get familiar than something that looks like everything else.

I haven't looked at in depth at the lpdf, I'm just responding to the policy. But here's a simple example of where we keep the lpdf and rng together when we don't strictly need to and I think it's the right decision: normal.

I expect this to throw an error: `normal_lpdf(x, mu, 0);` (where `x` and `mu` are some valid numbers). We don't need to throw an error -- we could have actually returned `-inf`, but the use case that we're designing for is for Stan. We want to provide useful error messages as soon as possible. If this returns `-inf` and that just propagates, we end up with an iteration being rejected with no indication to the user that the problem is in the evaluation of the normal distribution.

Now... we could have different bounds on the rng and expect `normal_rng(mu, 0);` to return `mu`, but right now it throws an exception. I'm perfectly happy with that. If someone actually passes in a `0` for the standard deviation, I think it's either a user not realizing they're just asking for `mu` back (in which case the error seems perfectly reasonable) or the user is trying to do it intentionally to either roll the base rng forward or do something really clever. Clever developers can find other ways to do that... I'd rather help the dev that doesn't know that they're doing something nonsensical.

**Comment by syclik** [comment]
@peterwicksstringfield and @bob-carpenter, I'll post back when I put this up on the wiki.

**Comment by peterwicksstringfield** [comment]
No particular reason for the rng to be different than the lpdf here. I have changed gaussian_dlm_obs_rng to throw domain_errors in response to positive semi-definite C0s, just like gaussian_dlm_obs_lpdf.

I have not pushed that change to the PR yet. And there are a couple other changes, and some error handling I need to clean up. And since it seems like I'm on the right track, I plan to do the other rngs on this ticket too.

Not ready for review. Will push changes soon and comment here again. I can close the PR in the meantime if that helps.

bob-carpenter, syclik thank you for the help.

**Comment by bob-carpenter** [comment]
Thanks for the status report---it's really helpful.

I'd suggest working depth first to get a couple functions fully
through review.  

It's easier on the reviewers and less rewriting for you if basic
structure needs to change.

**Comment by peterwicksstringfield** [comment]
The pull request with the first four RNGs is now ready for review.

https://github.com/stan-dev/math/pull/1083
