### ISSUE TITLE
Investigate ODE system's memory safety

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#1108]
## Description
There have been a couple of alarming issues that have popped up sporadically around the ODE system. 

1) the ODE system (and only the ODE system) [appears to fail](https://discourse.mc-stan.org/t/running-tests-with-sanitizers/3235) running with Clang's Address Santizer
2) the ODE system [causes segfaults](https://discourse.mc-stan.org/t/windows-rstudio-crashing-with-rstan-model-loaded/6545) when used on Windows with RTools 4.9.3
3) The ODE tests sporadically failed on at least[ one unrelated PR](http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1093/11/pipeline)

I think it would behoove us to send someone down to investigate. Source code review may help, but I'd also recommend running with Valgrind and the clang analyzer tool suite (like the [address sanitizer](https://clang.llvm.org/docs/AddressSanitizer.html)) to try to pinpoint issues.

#### Current Version:
v2.18.1

**Comment by wds15** [comment]
Before anyone digs into this, I think we should merge the sundials 4.0.1 pr.

**Comment by syclik** [comment]
I had an illuminating discussion with @wds15 on Monday and figured out some of how the ODE stuff got refactored.

At a high level:
- `coupled_ode_system.hpp` implements the interface that's required by odeint (Boost's ode solvers)
     * [`stan/math/prim/arr/functor/coupled_ode_system.hpp`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/arr/functor/coupled_ode_system.hpp)
     * [`stan/math/rev/arr/functor/coupled_ode_system.hpp`](https://github.com/stan-dev/math/blob/develop/stan/math/rev/arr/functor/coupled_ode_system.hpp)
- `cvodes_ode_data.hpp` and `coupled_ode_observer.hpp` implements the interface that's required by CVODES.
    * [`stan/math/rev/mat/functor/cvodes_ode_data.hpp`](https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/functor/cvodes_ode_data.hpp)
    * [`stan/math/prim/arr/functor/coupled_ode_observer.hpp`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/arr/functor/coupled_ode_observer.hpp)

@wds15 can correct me if I misunderstood the purpose of these classes. After discussing with @wds15, things became a lot clearer and I think we can simplify a lot. And document it so it's clear what the purpose of all these classes are. For example, since the `coupled_ode_observer` is only used for CVODES, I think it makes sense to just implement one class that handles the interface to CVODES. It would make sense to split apart the actual work that needs to be done for the ode integrators from the adapter classes that need to implement interfaces for the ode integrators we use. That'll help us move a little faster and make it easier to debug.

**Comment by wds15** [comment]
With the changes in the time-varying ode PR things change slightly. The `coupled_ode_observer` is used to adapt the outputs of any of the integrators into the AD system.

If you will we have:

- `coupled_ode_system` defines the sensitivity ODE RHS. It is written in a way such that we can plug it straight into odeint.
- `cvodes_ode_data` is a callback object for CVODES. This thing is essentially an adapter for the CVODES system for the sensitivity ODE RHS defined by `coupled_ode_system`. However, this callback also supplies the Jacobian wrt to the states needed for the stiff solver.
- `coupled_ode_observer` is an adapter which maps the output of any of the integrators to the AD tree of Stan.

I am not sure that we can simplify further.

**Comment by rok-cesnovar** [comment]
We run tests with `CXXFLAGS += -fsanitize=address` and everything seems to pass and I have not seen an ODE test fail (at least that I can remember) so closing this issue.
