### ISSUE TITLE
bugfix/gp_matern52_cov-translation-fails

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#1175]
## Description
This is in reference to stan-dev/stan#2739 that's failing on stan-dev/stan. 

I'm getting some compilation error that throws because I've used a function name as a variable name.

## Expected Output
stan-dev/stan passes all tests.

#### Current Version:
v2.19.0

**Comment by syclik** [comment]
@drezap, can you add more detail about what this bug is? I'm looking at the PR and there isn't information about the bug here. It looks like there's some description in the Stan repo, but it's not specific enough for me to understand what's going on.

Is there a test case that fails before the change is applied?
