### ISSUE TITLE
Redundant Definitions of the Incomplete Beta Function

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1237]
## Description
There are two definitions of the incomplete beta function, both of which delegate to ```boost::math::ibeta```:

## Example
```prim/scal/fun/ibeta.hppp```:
```
inline double ibeta(double a, double b, double x) {
  check_not_nan("ibeta", "a", a);
  check_not_nan("ibeta", "b", b);
  check_not_nan("ibeta", "x", x);
  return boost::math::ibeta(a, b, x);
}
```

```prim/scal/fun/inc_beta.hppp```:
```
inline double inc_beta(double a, double b, double x) {
  using boost::math::ibeta;
  return ibeta(a, b, x);
}
```

This could be tricky to deal with, as some users may be using ```ibeta``` while others are using ```inc_beta``` and removing either will break programs. May have to deprecate one of them moving forward.

#### Current Version:
v2.19.1

**Comment by andrjohns** [comment]
> some users may be using ibeta while others are using inc_beta

This turned out not to be an issue, as ```ibeta``` isn't exposed in the stan language, only ```inc_beta```. I've searched the Stan, Cmdstan, Rstan, and Pystan repos, and ```ibeta``` isn't called or defined anywhere within them.

Based on this, I'd say it was safe to remove ```ibeta``` from the math library altogether

**Comment by bob-carpenter** [comment]
The underlying implementations are different.  I only tested `inc_beta` in the new test framework as it looks like `ibeta` isn't used anywhere.

**Comment by peterwicksstringfield** [comment]
I've been looking into this.

The ibeta family includes these files:
```
    stan/math/prim/scal/fun/ibeta.hpp
    stan/math/rev/scal/fun/ibeta.hpp
    test/unit/math/prim/scal/fun/ibeta_test.cpp
    test/unit/math/rev/scal/fun/ibeta_test.cpp
```

This family is not exposed to Stan users, and is unused inside the math library. It has not been upgraded to the new expect_ad framework, as mentioned above, and it is the only user of the test_nan utility function, which could otherwise be deleted. ibeta(double, double, double) is distinguished from inc_beta(double, double, double) because ibeta uses the default Boost policies, not Stan's customized ones. ibeta does not support forward mode; there are only two overloads, ibeta(double, double, double), and ibeta(var, var, var). ibeta defines customized varis for all reverse-mode combinations (vvd, vdd, etc.), but it only uses its vvv vari, the other 6 are dead-code. ibeta(double, double, var) and so forth are supported via implicit conversion to var. The derivative computations in these varis predate those for inc_beta.

Also, the derivatives are wrong: #XXX.

The inc_beta family includes these files:
```
    stan/math/prim/scal/fun/inc_beta_dda.hpp
    stan/math/prim/scal/fun/inc_beta_ddb.hpp
    stan/math/prim/scal/fun/inc_beta_ddz.hpp
    test/unit/math/prim/scal/fun/inc_beta_dda_test.cpp
    test/unit/math/prim/scal/fun/inc_beta_ddb_test.cpp
    test/unit/math/prim/scal/fun/inc_beta_ddz_test.cpp

    stan/math/prim/scal/fun/grad_inc_beta.hpp
    stan/math/fwd/scal/fun/grad_inc_beta.hpp
    stan/math/rev/scal/fun/grad_inc_beta.hpp

    stan/math/prim/scal/fun/grad_reg_inc_beta.hpp
    test/unit/math/prim/scal/fun/grad_reg_inc_beta_test.cpp
    test/unit/math/fwd/scal/fun/grad_reg_inc_beta_test.cpp
    test/unit/math/mix/scal/fun/grad_reg_inc_beta_test.cpp

    stan/math/prim/scal/fun/inc_beta.hpp
    stan/math/fwd/scal/fun/inc_beta.hpp
    stan/math/rev/scal/fun/inc_beta.hpp
    test/unit/math/mix/scal/fun/inc_beta_test.cpp
```

This is the version exposed in Stan, and used internally by, among others, neg_binomial_cdf. It seems like a lot of work has gone into working out good analytic derivatives for inc_beta.

inc_beta is missing prim tests, we can salvage ibetas.

See PR #XXX for the fixes. 

inc_beta has effectively only three overloads; inc_beta(double, double, double), inc_beta(fvar<T>, fvar<T>, fvar<T>), inc_beta(var, var, var), with other combinations supported by promotion to autodiff types. We can easily do better, without doing any additional math, but that's a separate issue: #XXX.
