### ISSUE TITLE
Prim functions pass by value rather than reference

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1247]
## Description
Almost all of the functions in ```prim/scal/fun``` pass by value and use overloads to work with both ```double``` and ```int``` inputs. We can use template specialisations to work with both primitive types and pass by reference at the same time

## Example
Currently, ```asinh```:
```
inline double asinh(double x) { return std::asinh(x); }

inline double asinh(int x) { return std::asinh(x); }
```
Can be replaced with:
```
template <typename T>
inline typename std::enable_if_t<std::is_arithmetic<T>::value, double>
  asinh(const T& x) {
    return std::asinh(x);
  }
```
#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
Please do not make this change.  

First, primitives should be passed by value.   It's not terrible to pass them by constant reference, but we generally want to pass them by value.  All the style guides agree on this.  So if you do want to make this change, it shouldn't be `const T& x`, but just `T x`---you don't even need the `const` with primitives as they aren't references and hence can't be modified (i.e., adding `const` doesn't change the API, because `const double` and `double` mean the same thing to a client).

I don't think you want to do this:

```
template <typename T>
inline typename std::enable_if_t<std::is_arithmetic<T>::value, double>
  asinh(const T& x) {
    return std::asinh(x);
  }
```

If you are going to use the fully qualified `std::asinh`, then the only values that are going to compile are ones that match the [asinh library function](https://en.cppreference.com/w/cpp/numeric/math/asinh), which means only built-in primitives (float, double, long double, and all the built-in integer types).  So I don't think you need the `is_arithmetic` qualifier.  Are you worried about ambiguities with forward or reverse overloads?

**Comment by andrjohns** [comment]
> First, primitives should be passed by value.

I should have read up on performance costs of passing primitives by reference as well, this would not have a positive effect.

>  So I don't think you need the is_arithmetic qualifier.

This was based on @syclik's review comment about consistency between prim/rev/fwd with using template specialisations vs function overloads

**Comment by syclik** [comment]
@andrjohns: sorry about leading you down a dead end. That comment was meant for that function (is_nan); I hadn't thought through the consequence of it across everything else.

**Comment by bob-carpenter** [comment]
I don't think pass-by-constant-reference is a dealbreaker for primitives if you want to generically template.  It's just not the recommended signature just for primitives.
