### ISSUE TITLE
Reorganize the /opencl folder

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1352]
## Description
We currently have all the OpenCL function directly in the `/opencl` folder. We have already discussed this a few time but with the coming compiler support this should be done sooner rather than later.

My proposal (open to suggestions): 
- all `matrix_cl` overloads of `/prim/mat` functions should go to `/opencl/prim`
- all future overloads of `/rev/mat` functions will go to `/opencl/rev`
- core files stay in the `/opencl` (`context, kernel, matrix_cl, ...`)
- kernels stay in `/opencl/kernels`
- other `matrix_cl` functions that are not overloads of any existing Stan Math function stay in `/opencl` (a subfolder like /helpers is another option idk).

I can tackle this one once at least @SteveBronder and @t4c1 express their opinion.

## Expected Output
More organized files.

#### Current Version:
v2.20.0

**Comment by t4c1** [comment]
That seems fine to me.

**Comment by SteveBronder** [comment]
I'm fine with it!

**Comment by alashworth** [comment]
If you guys are reorganizing the folder, what do you think about the unit tests? Is it possible to move all OpenCL specific tests to the test/unit/opencl folder? 

AFAIK this means             
prim/mat/fun/mdivide_left_tri_test.cpp
rev/mat/fun/cholesky_decompose_test.cpp
would have to move. 

Then going forward this would enable an optimization where I only compile the OpenCL folder unit tests in order to test the OpenCL configuration. Though, I do not know if this is valid wrt code coverage.

**Comment by rok-cesnovar** [comment]
The plan is to move everything OpenCL related out of the /prim and /rev. So anything that will use the OpenCL API will be in /opencl. That will make things more encapsulated and easier to maintain. 

But in order for us to do that and still have these functions use GPUs we need to add compiler support, which isnt far of but isnt there yet.

For the time being we can move the tests behind #ifdef STAN_OPENCL guards to /opencl. I think that is reasonable.

**Comment by SteveBronder** [comment]
prim/mat/fun/mdivide_left_tri_test.cpp
rev/mat/fun/cholesky_decompose_test.cpp

These are both tests that check the CPU and OpenCL code right? idt we want to move that to the OpenCL folder

**Comment by rok-cesnovar** [comment]
Yes, but we can split out the OpenCL vs CPU comparison tests to a separate file. There will be some test duplication.
