### ISSUE TITLE
Add ## Release Notes to the PRs template

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1357]
## Description

It may be nice to add a section to the PR template like below so that releases can just copy paste the into there for making release notes

---------------------------------------

## Release Notes

Include here what should be in the release notes for when this pull request is accepted

--------------------------------------

#### Current Version:
v2.20.0

**EDIT: Removed the stuff about getting rid of issues for PRs

**Comment by wds15** [comment]
+1

**Comment by rok-cesnovar** [comment]
My optimal decision rule for issues: 
- found a bug -> make an issue
- have an idea for a refactor/feature/... but dont have the time do to it (or dont want to do it but feel it would be great if someone does it)-> make an issue so someone else can start (maybe future-you with more time :) )
- have an idea for a refactor/feature/... and you already started or will start immediately -> open a PR with release notes
- starting a new project (larger feature) that will be done over multiple PRs -> make an issue (if its a project that will span over more repos maybe a design doc?)

I agree that it feels kind of silly to post an issue and then immediately solve it with a PR 5 minutes later. In theory keeping the larger overview debate on the issue sounds great. But in practice we just have the same discussion on two ends. 

There is also a bunch of open issues across Stan Math/Stan/Cmdstan that were fixed with a PR but were never closed. That interferes with my zero-inbox OCD heavily :) But I feel bad spamming poeple to double-check with "is this still a thing emails".

**Comment by bob-carpenter** [comment]
> I feel bad spamming poeple to double-check with "is this still a thing emails".

Please don't!  Ideally, there'll be a commit message with "fixes #XYZ" to auto-close issues, but if not, pinging people is the way to get things closed.   Or just use your judgement.  If an issue is accidentally closed, it's not a huge deal if it's not a critical bug fix.

I like having an issue per PR just to simplify the whole process.  I know it may be a bit more work to create an issue and then solve it, but it reduces decision points.  Not a huge deal to me either way, though.

**Comment by SteveBronder** [comment]
I'm okay with having an issue per PR if it's easier for other people. Especially for bug fixes etc. agree it would get too wishy-washy.

Though I think it would be easier for each release if we put in a release notes section, I'll make a PR for it and we can see whether that's good or bad

**Comment by syclik** [comment]
It is definitely easier in the GitHub interface using issues to handle what's happening in the codebase. This is a property of using GitHub. They've come a long way in their interface to making issues and PRs searchable, but issues and PRs are actually handled differently.

Ideally, issues describe what happens. Either an issue or feature request. And it should be pretty minimal. Reading titles should be enough of a picture of what's happening.

PRs are code that fixes the issue or pull request. When issues get closed with PRs, we know they're done. One PR can close multiple issues... there's a practical difficulty in closing too many with one PR: it's tough to review. It's a lot easier to review a PR when it's short and has one thing it focuses on. When there are a handful of different issues, it's really hard to review.

---

For concreteness:

This is the list of issues that were closed recently: [this list is reachable in a few clicks](https://github.com/stan-dev/math/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc)

This is the list of PRs that were closed recently: [this list is (now) reachable in a few clicks](https://github.com/stan-dev/math/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)

If we have PRs with notes inside, in order to build release notes, we need to walk through all the issues + walk through every PR and pick out the information inside the ones that have notes on them.

There is an alternative option... if we can automate this completely, we can do whatever with issues and PRs.

**Comment by SteveBronder** [comment]
Those are some rad links! I updated the original issue at the top to reflect you and Bob's opinion on keeping issues.

> If we have PRs with notes inside, in order to build release notes, we need to walk through all the issues + walk through every PR and pick out the information inside the ones that have notes on them.


What is the current process for making the release notes? If you already have a good system for it then no need to rock the boat and we can close this issue. My sense here was that you could use the recently closed PR link you posted above to jump in and just copy-pasta the release notes each PR wrote.

> There is an alternative option... if we can automate this completely, we can do whatever with issues and PRs.

@emilyriederer wrote the `projmgr` R package that can grab github stuff for us. They have [`get_issues`](https://emilyriederer.github.io/projmgr/reference/get_issues.html). If we made a PR on their repo for `get_pull_requests` and added a `Release Notes` section to our template then we could just have a script that puts all the release notes together.

Though again if this is too small a piece of the release to be worth automation then let's not over optimize
