### ISSUE TITLE
lub_constrain boundary behaviour

### ISSUE THREAD

**Issue by nhuurre** [stan-dev/math#1441]
## Description

Remove the conditional

```
 if ((x > NEGATIVE_INFTY) && (inv_logit_x == 0))
    inv_logit_x = 1e-15;
```

from the definition of `lub_constrain()` in `stan/math/prim/scal/fun/lub_constrain.hpp`.

### Background

The parameter constraining transform `lub_constrain()` has an code path with a comment
```cpp
// Prevent x from reaching zero unless it really really should.
```
The limiting value `1e-15` chosen is so large as to make the transform non-monotone. The branch also cannot prevent rounding when the lower bound is not zero. e.g. `<lower=100,upper=101>` does not see any effect, other than it stopping derivative propagation.
Similar code is _not_ present in `lb_constrain()` which is allowed to round to the boundary value.

A related question is what to do about the unconstraining transform `lub_free()`. The `check_bounded()` is inclusive so values at boundaries are accepted but the logit function maps boundary to infinity so it will fail later. A reasonable choice might be to map the boundary values to some finite number beyond the rounding limit. However, the rounding limit depends on the bounds in a complex fashion.

#### Current Version:
v3.0.0

**Comment by bob-carpenter** [comment]
Thanks for filing.  Is there a proposed behavior change?  I'd be OK with it throwing exceptions or just rounding.

**Comment by nhuurre** [comment]
Stan manual says declared bounds are inclusive. "Just rounding" is the expected behavior. It's also effectively the current behavior when bounds are far from zero. The only weird thing about just rounding is that `lub_free(lub_constrain(x))` might not be finite even if `x` is.

**Comment by bob-carpenter** [comment]
> On Nov 8, 2019, at 1:21 AM, Niko Huurre <notifications@github.com> wrote:
> 
> Stan manual says declared bounds are inclusive.

Right, that was the original intention.  It also makes the real and int cases equivalent
in that they are inclusive boundaries.

But it wasn't particularly well thought out for reals and what would happen downstream
when plugged into something like a beta or a binomial.

> "Just rounding" is the expected behavior.

That's how we coded it.  

> It's also effectively the current behavior when bounds are far from zero. The only weird thing about just rounding is that lub_free(lub_constrain(x)) might not be finite even if x is.

Right.  We also tried to get the constraints the other way around to make sense, so that exp(-inf) = 0 and you could round trip from constrained (0) to unconstrained (-inf) and back.  But we never got the derivatives right for any of this;  they often only exist one-sided. 

I'm just saying we should probably think through again what the right behavior is.

**Comment by nhuurre** [comment]
Currently the code in [lub_constrain](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/fun/lub_constrain.hpp#L63) is
```cpp
  inv_logit_x = inv_logit(x);
  if ((x > NEGATIVE_INFTY) && (inv_logit_x == 0))
    inv_logit_x = 1e-15;
  return fma((ub - lb), inv_logit_x, lb);
```
The inverse logit does not underflow even when the result is very small.
```
  inv_logit(-35) = 6e-16
  inv_logit(-700) = 1e-305
  inv_logit(-750) = 0.0
```
That means the transform goes to very small values before jumping back up to 1e-15. When the lower bound is not zero that `fma()` will round these tiny numbers to the boundary.
A better option would be
```cpp
  t_x = fma((ub - lb), inv_logit(x), lb);
  if ((x > NEGATIVE_INFTY) && (t_x == lb))
    t_x = boost::math::float_next(lb);
  return t_x;
```
A single ulp difference isn't very robust. I believe the best choice is to simply remove the branch entirely.

**Comment by bob-carpenter** [comment]
Yes, the branch is definitely bad news for precision.  I'm embarrassed it's in there---we were just learning floating point when writing v1 of Stan.  

My question was mostly about whether we should be throwing an exception if we hit the round-to-0 or round-to-1 point.  We can get to within 1e-300 of 0 but only to within about 1e-16 of 1 before rounding.  The derivative is inv_logit'(x) = inv_logit(x) * inv_logit(-x), which rounds as the best of inv_logit(x) and inv_logit(-x) because the other rounds to 1.

**Comment by avehtari** [comment]
Some thoughts, which I expect others have been thinking, too, but couldn't find summarized.

There is a general problem that real values are not exactly continuous, but discrete with floating point representation. In the idealized world the bounded variables often have non-inclusive bounds (e.g. strictly positive values). If Stan `lower` and `upper` would define non-inclusive bounds, it would depend on the bound value how close the closest floating point value is. In that sense, it seems more clear if Stan `lower` and `upper` would define inclusive bounds (which would match also with int type). Of course, even then if the numeric string used to present the bound can not be represented exactly with floating point represented, the stored fp value for the bound can be smaller or larger than the value presented by the numeric string.

It seems difficult to check when the fp presentation of the bound is different than the numeric string in Stan code. Bounds can be also computed on the fly, e.g. `<lower=alpha>`, where the accuracy of computation for alpha is usually unknown for the user.  Recently, in combination with ode, we saw negative values for parameter with constraint `<lower=0>`, and then got error in constraint checking. I didn't know before that this could happen.

For `<lower=0>`, most of the time the accuracy near 0 is sufficient and users don't see 0's which could cause problems in other parts of the code. Sometimes users write something like `<lower=0.0000001>`, and this has been openly criticized as bad practice, but it seems that floating point presentation is causing more headache than previously thought. Maybe we should say in Stan reference manual that e.g. `<lower=0.0000001>` is fine, if you want have strictly positive values.

> The only weird thing about just rounding is that lub_free(lub_constrain(x)) might not be finite even if x is.

This holds in general for floating point math, e.g. `log(exp(x)+exp(y))` might not be finite even if `x` and `y` are. I think it means that there should not be premature "limiting values", but instead let numerical issues to show and then require thinking numerically more stable computation, e.g. `log_sum_exp`.

I think it would be good to extend the discussion in Stan reference manual
section "Univariate Data Types and Variable Declarations" about the floating point problems (I think, the current version says this bit too briefly). Or add pointer to Stan User's guide chapter "14 floating point arithmetic" and more discussion there. The current version has only:

> Real variables may be bounded using the same syntax as integers. In theory (that is, with arbitrary-precision arithmetic), the bounds on real values would be exclusive. Unfortunately, finite-precision arithmetic rounding errors will often lead to values on the boundaries, so they are allowed in Stan.
>
> The variable sigma may be declared to be non-negative as follows.
> ```
> real<lower=0> sigma;
> ```

**Comment by bob-carpenter** [comment]
>  Recently, in combination with ode, we saw negative values for parameter with constraint <lower=0>, and then got error in constraint checking. I didn't know before that this could happen.

The inverse tansform is `exp(x)` from unconstrained `x`.  Does that mean `exp(x)` can be negative?  It should just round to 0 for values below about -400 or so.  I assume we're still using `std::exp`---anything could happen if we use someone else's approximation.

> If Stan lower and upper would define non-inclusive bounds,

Mathematically, the inverse transforms make the continuous bounds non-inclusive.  As you indicate, the problem is that rounding will lead to boundary values.  For example if the unconstrained vlaue is -500, the constrained value will be 0 for `lower = 0`.  

The question I was raising is whether we should just throw an exception when we get non-inclusive bounds.

> Maybe we should say in Stan reference manual that e.g. <lower=0.0000001> is fine, if you want have strictly positive values.

Then if the unconstrained value is -500, then the constrianed value is 1e-7 and the gradient is zero, becuase `exp(-500) = 0` and `exp'(-500) = 0` with double-precision floating point.  This seems like it'll introduce the same problem as that 1e-15 lower bound in ` lub_constrain`.

> I think it means that there should not be premature "limiting values", but instead let numerical issues to show and then require thinking numerically more stable computation, e.g. log_sum_exp.

This sounds like the right approach to me.  That's why I'm wondering if we should just be throwing exceptions when we get catastrophic rounding to 1 (very common given limited dynamic range around 1), underflow to 0 (less likely), or overflow to +/- infinity (again less likely).

> I think it would be good to extend the discussion in Stan reference manual
section "Univariate Data Types and Variable Declarations" about the floating point problems

Makes sense.  I created [an issue in stan-dev/docs](https://github.com/stan-dev/docs/issues/110) to do just that.

**Comment by avehtari** [comment]
> Then if the unconstrained value is -500, then the constrianed value is 1e-7 and the gradient is zero, becuase exp(-500) = 0 and exp'(-500) = 0 with double-precision floating point. This seems like it'll introduce the same problem as that 1e-15 lower bound in lub_constrain.

I momentarily forgot that we need to think gradients, too. It seems that the relevant discussion should mention that the gradient computation can have different floating point accuracy than the constrained value, and the gradient can be zero or fluctuating even if the constrained value is not yet at the boundary value.

>  That's why I'm wondering if we should just be throwing exceptions when we get catastrophic rounding to 1 (very common given limited dynamic range around 1), underflow to 0 (less likely), or overflow to +/- infinity (again less likely).

I guess there exists counterexamples where rounding to 1 or underflow to 0 is not catastrophic. At least it should not cause sampling to stop completely, but even a reject might be too much?

**Comment by betanalpha** [comment]
A mildly tangential comment — the issues with the current lub_constrain
behavior is not so much poorly handling of the overflow but rather that it 
makes the output non-monotonic and hence hard to understand. 
Boundary behavior is a lot easier to reason about when the floating point 
values are at least monotonic 

> Recently, in combination with ode, we saw negative values for parameter with constraint <lower=0>, and then got error in constraint checking. I didn't know before that this could happen.

This was with a parameter that was being explored by the Markov chain or 
the states defined by the ODE?  The latter definitely can run into problems
because of floating point in the ODE solver unless you solve the log states
themselves and then exponentiate afterwards.

If the former then what was the constraint?

> For <lower=0>, most of the time the accuracy near 0 is sufficient and users don't see 0's which could cause problems in other parts of the code. Sometimes users write something like <lower=0.0000001>, and this has been openly criticized as bad practice, but it seems that floating point presentation is causing more headache than previously thought. Maybe we should say in Stan reference manual that e.g. <lower=0.0000001> is fine, if you want have strictly positive values.
> 
To be honest I don’t think that there have actually been many headaches 
with floating point.  Most of the examples being discussed are somewhat 
pathological from a modeling perspective and so the stress on the floating
point is somewhat artificial.  It may be more productive to figure out models
motivated by actual applications that run into problems and then reduce
them to a suite of minimally failing examples.

> I think it means that there should not be premature "limiting values", but instead let numerical issues to show and then require thinking numerically more stable computation, e.g. log_sum_exp.
> 
> This sounds like the right approach to me. That's why I'm wondering if we should just be throwing exceptions when we get catastrophic rounding to 1 (very common given limited dynamic range around 1), underflow to 0 (less likely), or overflow to +/- infinity (again less likely).
> 
> I guess there exists counterexamples where rounding to 1 or underflow to 0 is not catastrophic. At least it should not cause sampling to stop completely, but even a reject might be too much?
> 
It depends on how pedantic we want to be.  If the floating point calculations
are questionable then the validity of the entire calculation can’t be guaranteed
and so if we wanted to be really, really careful we’d terminate instead of just
giving a warning or rejecting the current transition.  In fact rejecting would 
change the target distribution a bit so we’d have to be careful to not do that 
without providing some context to the user.

In general I think the most robust framework is to have each function responsible 
for handling inputs at boundary values and reacting appropriately (especially 
with regard to the gradients).  The only thing that we wouldn’t be able to 
handle would be catastrophic cancellations, especially in terms that get automatically
added like the constraint Jacobians.  But maybe there the best approach is to
build functions desired for better boundary behavior — for example a beta
density that takes in an unconstrained value and handles the constraints 
internally to handle the boundary behavior better.
> I momentarily forgot that we need to think gradients, too. It seems that the relevant discussion should mention that the gradient computation can have different floating point accuracy than the constrained value, and the gradient can be zero or fluctuating even if the constrained value is not yet at the boundary value.
> 
Yes!  For example the density functions are somewhat robust to boundary values 
but the gradients are not nearly as examined.

**Comment by bob-carpenter** [comment]
> On Dec 7, 2019, at 2:32 PM, Michael Betancourt <notifications@github.com> wrote:
> 
> A mildly tangential comment — the issues with the current lub_constrain
> behavior is not so much poorly handling of the overflow but rather that it 
> makes the output non-monotonic and hence hard to understand. 
> Boundary behavior is a lot easier to reason about when the floating point 
> values are at least monotonic 

Right---the issue is only addressing the non-monotonicity by removing the conditional.


> > This sounds like the right approach to me. That's why I'm wondering if we should just be throwing exceptions when we get catastrophic rounding to 1 (very common given limited dynamic range around 1), underflow to 0 (less likely), or overflow to +/- infinity (again less likely).
> > 
> > I guess there exists counterexamples where rounding to 1 or underflow to 0 is not catastrophic. At least it should not cause sampling to stop completely, but even a reject might be too much?
> > 
> It depends on how pedantic we want to be. If the floating point calculations
> are questionable then the validity of the entire calculation can’t be guaranteed
> and so if we wanted to be really, really careful we’d terminate instead of just
> giving a warning or rejecting the current transition. 

After warmup, as issues like this during warmup may be recoverable. Otherwise, it might make sense to treat like a divergence---keep going, but provide a stern warning.

> In fact rejecting would 
> change the target distribution a bit so we’d have to be careful to not do that 
> without providing some context to the user.
> 
> In general I think the most robust framework is to have each function responsible 
> for handling inputs at boundary values and reacting appropriately (especially 
> with regard to the gradients). 

That was how we were looking at it, but we haven't been consistent. I'm not even sure it's possible to be consistent in this.

**Comment by betanalpha** [comment]
> That was how we were looking at it, but we haven't been consistent. I'm not even sure it's possible to be consistent in this.

Right — all we can do is maintain consistency within the context of
a given function.  That leaves us unable to handle cancellations between
Jacobians and densities when dealing with constrained parameters.
One possibility is to create the push forward unconstrained densities 
explicitly as new functions and maybe let the compiler dispatch to those
instead of just aggregating the Jacobians and densities separately.
