### ISSUE TITLE
Windows compiler segfaults

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1615]
## Description

We are experiencing some compiler segmentation faults lately on Jenkins Windows machines. These are most probably related to the flatten and limitations of g++ 4.9.3. 

If the flatten and increased file sizes is not the culprit I would suspect PR https://github.com/stan-dev/math/pull/1471 that introduced additional templating. 

Examples of failures:

https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1603/9/pipeline/
https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1610/4/

If anyone sees a similar error on Jenkins please post it here! And if anyone can replicate this locally, also please post more info. So far I was unable to replicate locally. 

We have 4 more days until the release to figure out:
- how to avoid this
- if this only effects the Jenkins machines

#### Current Version:
v3.0.0

**Comment by andrjohns** [comment]
Thanks for catching this! I've got a similar issue here:

https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1148/pipeline

The math tests pass on Windows, but the downstream tests segfault.

**Comment by rok-cesnovar** [comment]
@t4c1 brought this to my attention. I am now trying to get a reliable way to replicate this locally or on Jenkins. It seems that https://github.com/stan-dev/math/pull/1558 is experiencing this issue the most reliably on the upstream test. Will branch off of that and abuse Jenkins for debugging a bit.

Its probably either the master includes like <stan/math/prim/err.hpp> or the added templating. I am hoping its the first, as the latter would be really disappointing.

**Comment by mcol** [comment]
Not sure if you need other reports, but here's one: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1612/9/pipeline/174

**Comment by rok-cesnovar** [comment]
Thanks to everyone tagging me, I should have time to get to the bottom of this tomorrow.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal quick question. Can you tell me anything about which Windows machine was used for this two tests: 
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1147/pipeline/66
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1148/pipeline/66

and these two:
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1149/pipeline/66
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1150/pipeline/66

Or even better, tell me where I can look that for myself if at all possible. I know you probably told me this a couple of times, sorry :)

**Comment by serban-nicusor-toptal** [comment]
Stan, downstream_tests, 1147: `Running on gelman-group-win-new`
Stan, downstream_tests, 1148: `Running on gelman-group-win-new`
Stan, downstream_tests, 1149: `Running on gelman-group-win-new`
Stan, downstream_tests, 1149: `Running on gelman-group-win2`

Getting this through Jenkins is a pain because Chromes just hangs with more than 4MB data on a page ( even on high-end pcs ).
So what I do is the following:
1. Download the log with `wget`, since Jenkins is part public anyone can do it without authentication or tokens.
`wget https://jenkins.mc-stan.org/job/Stan/job/downstream_tests/1150/consoleText`
2. Open that file in an editor like Visual Studio Code then simply `CTRL + F` after `Running on` and you'll see what machines were used for that particular job.

I'm currently in the process of building more detailed documentation about Jenkins from jobs to debug procedures so it brings a bit more transparency and others can review CI/CD stages and spot issues more easily. 

If I can help with anything else please let me know!

**Comment by rok-cesnovar** [comment]
Thanks, that more or less confirms it that is not an issue related to a specific machine. I am still struggling to reproduce this locally. 

How much RAM is given to Jenkins on Windows? The first issue some time ago was that it was only allowing it to use 1GB of RAM right? How much does it have now? That could potentially be an issue here, since more C++ templating and using master includes means more RAM is needed for the compilation stage.

**Comment by serban-nicusor-toptal** [comment]
Just Jenkins java process was affected by RAM limits, I was wrong in thinking that it will affect processes ran by it. So any process ran by Jenkins will use all the available RAM.
What I found out while fixing some bugs is that some jobs require more swap that the default allocated. Windows allocate around 50 MB which is very low so I had to increase it. Can't give you exact amount/server now but I will update the below when I get home. ( forgot to add swap specifications )
If you want to see other machine specs I've made a list [here](https://github.com/stan-dev/ci-scripts/blob/refactor-jenkins-docs/docs/agents.md) note that it may change!

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal you fixed those swaps a few days ago right? There were no segfaults on Windows Jenkins tests for a day now and I still cant reproduce locally...

**Comment by serban-nicusor-toptal** [comment]
Hey, I've checked now and the windows machines have respectively 20 and 25 GB swap so more than enough.
To be honest I didn't change anything on the windows machines this week been writing docs.
The single anomaly I saw was that the new windows machine went a few times down,up in the past few days. Everything else was running fine.

**Comment by rok-cesnovar** [comment]
The ones with "internal compiler error: Segmentation fault" are related and those should be looked at. 

I looked at

https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1147/pipeline/66
https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1603/9/pipeline/
https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1610/4/
https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1148/pipeline/66
https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1612/9/pipeline/174

which all failed for this reason and they all ran on `gelman-group-win-new`. And none have failed in the last day. If anyone finds any other segfaults on windows, please keep posting those or tagging me.

**Comment by rok-cesnovar** [comment]
If these are limited to a single machine that doesnt have enough resources to handle this, that would be the best case scenario. We will just reduce the parallel env var and should be good.

**Comment by serban-nicusor-toptal** [comment]
All of the above are extracted from segfault jobs.
This is only related to RAM from what I understood and it's either that software is trying to access bad parts of the memory ( maybe a code/compiler issue in multi-threading ) or a faulty RAM stick. [Source](https://en.wikipedia.org/wiki/Segmentation_fault)
I would assume it's not related to just one machine since on both it failed and then succeeded.

**Comment by rok-cesnovar** [comment]
I am thinking more in the line that it segfaults as it runs out of RAM in multi-threaded compilation.
Have you seen any segfaults on `gelman-group-win2`? If we find any of those then its certainly not limited to one machine.

**Comment by serban-nicusor-toptal** [comment]
Yes, I've found one. Give me a sec to find it.
Will edit this comment.

**Comment by serban-nicusor-toptal** [comment]
You are actually right, it only happened on the new windows instance. The failures on the other one weren't related to segmentation fault.
I've rebooted the machine maybe it wasn't rebooted after swap increase ... ? That may be the case.
I've started [this job](https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1156/pipeline) it should pick `gelman-group-win-new` since `gelman-group-win2` is busy.

**Comment by rok-cesnovar** [comment]
Thanks!

**Comment by serban-nicusor-toptal** [comment]
I think this confirms it: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/1156/pipeline/66

**Comment by rok-cesnovar** [comment]
Thank you for the help. Closing for now, if any such error occurs again, we can reopen.

**Comment by wds15** [comment]
Thanks all for figuring this out!
