### ISSUE TITLE
return type and scalar type metaprograms generalized for complex

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1734]
## Description

New and generalized metaprograms.  Also pull tests into `mix` with generalization to avoid all the cut-and-paste and extend test coverage.

#### `scalar_type` (generalized)

Generalized so that if any of the arguments is `std::complex`, so is the result.  Deals with assignability of reals to complex, and of `std::complex<double>` to any `std::complex<T>` type. It's the right mathematical definition and will maintain backward compatibility.

#### `base_type` (new)

Like `scalar_type`, but takes the value type of complex numbers so the result is either a built-in arithmetic type or an autodiff type.

#### `XXX_return_t` (new)

Convenience wrappers for real, complex, standard vector, and Eigen matrix, vector, and row vector returns.  These wrap the base type with the specified type and are what I think we'll actually be using in programs.

#### `scalar_lub` (new)

Binary metaprogram to compute least-upper-bound in the assignability relation among scalars.

For return types, we generally want to pull out the least upper bound of the base types of the argument, then embed them as the base type of the result.  Currently, we have a metaprogram called `return_type_t` which is so-called because it pulls out the real return type required for all of our density functions.  I'm suggesting we deprecate 

#### Current Version:
v3.1.0

**Comment by t4c1** [comment]
I think even with the addition of complex numbers determining a scalar type is more useful than determining base type of complex numbers. So I would suggest to fix `scalar_type_t` to correctly determine complex scalars instead of deprecating it.

**Comment by bob-carpenter** [comment]
> I think even with the addition of complex numbers determining a scalar type is more useful than determining base type of complex numbers.

Complex numbers are both scalars and scalar containers.  It'd be easy to add, but I don't see a use case for a `scalar_type_t` that stops at the complex type.

We don't need it for either Eigen or the std::complex library implementation.  Eigen uses its own traits, which we have to specialize and the complex library doesn't have any binary functions.

For differentiable functions, the base type of the result is always the join (least upper bound) of the base types of the arguments with `double` included (so the result can never be `int).  The ordering is by (inverse) assignability in Stan:

* `var > double`
* `fvar<T> > double`
* `double > int`

The container type of the result depends on the function and can't be inferred generically, but is always a structure with a template parameter equal to the join of the base types.  So all those return type metaprograms I proposed are just simple utility wrappers around the the joins of the base types.

**Comment by t4c1** [comment]
When searching for example of where we need `scalar_type_t` I found it is not actually used in that many places. Most of those can be replaced by `value_type_t`. So I maybe we don't have a need for `scalar_type_t` after all.

**Comment by SteveBronder** [comment]
I def agree that `return_type_t` is confusing. It always feels like it was an internal equivalent for `auto` but just for "scalar" types when we want to declare a parameter ahead of use (`real_return_t` in the above). Though idk if I like breaking it up into multiple ones, what if a function can take in containers with both real and complex numbers?

I wrote a thing below but after re-reading above I don't think I'm hitting what the intent of this is so it may just be a wacky rant


-----------------------------------------

I've always thought of `value_type_t` and `scalar_type_t` as

`value_type_t<T>`: Returns the base storage type for containers and otherwise returns itself
- `value_type_t<Eigen::MatrixXd> = double`
- `value_type_t<std::vector<Eigen::MatrixXd>>> = Eigen::MatrixXd`
- `value_type_t<complex<double>> = double`
- `value_type_t<complex<complex<double>>> = complex<double>`

This mostly just comes from that std::vector etc has a `value_type` trait.

`scalar_type_t<T>`: Recursively iterates through containers returning the base storage type for the lowest level internal container and otherwise returns itself
- `scalar_type_t<Eigen::MatrixXd> = double`
- `scalar_type_t<std::vector<Eigen::MatrixXd>>> = double`
- `scalar_type_t<complex<double>> = double`
- `scalar_type_t<complex<complex<double>>> = double`

Before complex I think this made sense. I agree it's weird now. 

> When searching for examples of where we need scalar_type_t I found it is not actually used in that many places. Most of those can be replaced by value_type_t. So I maybe we don't have a need for scalar_type_t after all.

Yeah with the stuff above and how the math library actually works I think most of scalar_type_t could be removed.

Looking at how `return_type_t` [is used now](https://github.com/stan-dev/math/search?q=return_type_t&unscoped_q=return_type_t) it seems like 
1. [Return types for functions and methods](https://github.com/stan-dev/math/blob/47b0595203bd9df718940baedac19c48d4179af4/stan/math/prim/fun/variance.hpp#L22), which could probably just use auto.
2. [Declaring objects before they are used](https://github.com/stan-dev/math/blob/52e5a983ec0cc194ddc5ad4622f046e12f40a95c/stan/math/prim/fun/gp_exponential_cov.hpp#L44)

and I think that's it? For the return types tbh I bet we could get rid of like 60% of those with a grep and the others with something clever. So what we really seem to want out of `return_type_t` is a type trait that follows our promotion rules for declaring objects ahead of time. So I think we just want something that handles promotion rules

What if we 

1. Changed the name of `return_type_t` to `promote_type_t`?
2. Add logic for promotion rules of `return_type_t<complex<double>, complex<var>>`
3. Added `complex<>` as a `scalar_type_t` specialization so it returns one of the set of `var, fvar<>, complex<>, double, int`

It sounds like `value_type` gives you the thing you want for the base type?

**Comment by t4c1** [comment]
I agree with suggestions 1 and 2. 3 is the same as @bob-carpenter suggested, except he added the rename to `base_type`. I feel with this change `base_type` is a better name for this trait.

**Comment by bob-carpenter** [comment]
I updated the issue to reflect the forthcoming PR and match everyone's requests.  Thanks much for all the feedback.

I also pulled the any/all part of this into new issue #1735.

**Comment by bob-carpenter** [comment]
That's what I was trying to say.

But I already rewrote it to return complex types where approrpaite since that's the right mathematical definition and it was the path of least resistance going forward.  The rewrite's backward's compatible and my guess is we'll be able to just remove it in the future.

**Comment by bob-carpenter** [comment]
Also, it's not just an auto replacement.  We need it to
enable brace initializer returns and to eval when returns are matrices.  This may change, but auto isn't a valid substitute at the moment unless we change all of our returns to compensate for having auto.
