### ISSUE TITLE
Autodiffstackstorage instance compiling into too many translation units

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#1750]
## Description

We hit a segfault in develop R + gcc + rstan 2.21 + StanHeaders 2.21 + a package compiled with previous Stanheaders that appears to be a problem where the static class member variable here: https://github.com/stan-dev/math/blob/develop/stan/math/rev/core/autodiffstackstorage.hpp#L139 appears in multiple translation units.

If we remove the line linked and define that thing elsewhere, then we can get control over where this instance appears in the object files.

This issue is kindof a placeholder. Still need to confirm the bug. Will update with more info once it's confirmed this was a problem/there is a solution.

#### Current Version:
v3.1.0

**Comment by bbbales2** [comment]
The reason for putting this in math is that there should be .cpp files that compile against math without instantiating the AutodiffStackSingleton::instance_. Where that memory lives should be controlled by the thing compiling the code (and just including stan math shouldn't necessarily make it happen). Maybe.

**Comment by wds15** [comment]
What you write sounds right to me. The thing is if you move the declaration of the instance into a .cpp file, then you break backwards compatibility for stan-math - at least this used to be true in the past when it was header only. To require that a .cpp file is linked in makes things a lot more complicated for C++ stan-math users. As we already have now the TBB as a binary requirement to be linked in, things may be different now.

Last, but not least, we should performance test such a change which moves the instance declaration into a .cpp file of its own since the linker may do less of an optimization job, I think.

... but overall, I think it makes sense to me.

**Comment by bob-carpenter** [comment]
This is a bug, so we don't want backward compatibility.

The math library already links multiple translation units.  This bug got introduced when I split Stan into two translation units, one for the services and one for the model.  Before that, we introduced static linking for the Sundials library. 

The code itself isn't any more complicated, it's just built with one more translation unit.

What are you looking for in terms of performance testing beyond our
basic model tests in continuous integration?

The TBB is dynamically linked, which introduces an orthogonal dimension of pain, but I don't see how it's relevant here.

**Comment by wds15** [comment]
The tbb makes Stan math non header only which was not the case before...and this change does this as well from a different angle.

We also need to put the tbb observer in the init  chainsblestack file into its own cpp file.

The standard tests with some bumped number of replications do it for me.

**Comment by bgoodri** [comment]
It does intuitively make more sense to me that the user's model class (that defines `log_prob`) should instantiate whatever memory stuff it needs, rather than having it instantiated in compiled model_base class (in rstan > 2.19). However, for a package like rstanarm that comes with _multiple_ Stan programs, should each model class instantiate its own Autodiffstackstoreagesingleton or should be one of those in the rstanarm.so object that all of its models use?

**Comment by bob-carpenter** [comment]
>  the user's model class (that defines log_prob) should instantiate whatever memory stuff it needs,

I believe creating another translation unit for the memory is the solution @bbbales2 and I discussed and he figured out how to code and build.

> should each model class instantiate its own Autodiffstackstoreagesingleton

That wouldn't work because it's assumed to be a statically accessible singleton.  There could be a different one per thread, but not multiple existing in the same thread without serious re-engineering.

**Comment by bbbales2** [comment]
Compiling the separate translation unit is very fast and linking it is too.

In terms of rstanarm, I think we'd be discussing the difference in linking these things statically (in which case we'd bury the translation unit in one of the shared objects that get loaded by R) or we put it in its own shared object and make R load it.

I dunno what the options or preferences are. Presumably we could map it out.

Before we do that though I want to know if the separate translation unit thing actually solves the segfault problem.

**Comment by wds15** [comment]
Maybe we should first understand how the current rstanarm works with multiple models? From my understanding we have all along alway used multiple Autodiff stacks - one per model which is in the rstanarm.so file. What helped me recently understand things a bit better - but I am not yet fully "enlightened" is this article: http://techunravel.blogspot.com/2011/10/staticglobal-variable-and-shared.html

What could be worthwhile to do is to avoid that the autodiff instance gets compiled into the rstan.so, but into all the model translation units. That can be done already now by building rstan.so with the compile time flags

`-DSTAN_MATH_REV_CORE_AUTODIFFSTACKSTORAGE_HPP -DSTAN_MATH_REV_CORE_INIT_CHAINABLESTACK_HPP`

These need to go to the very beginning of the compile calls in order to abuse the header guards from the respective files. For each model being compiled we do not define these and then all should be good.

Now, this is all guessing and we are in the dark...we should probably emulate what happens in rstan (multiple models in a shared library) with cmdstan. When we get that to work, then rstan should be straightforward, no?

**Comment by bob-carpenter** [comment]
Thanks---that's really helpful understanding what's going on now.

For CmdStan, I don't think we need dynamic linking or multiple models
anywhere.

**Comment by bgoodri** [comment]
If I put `-DSTAN_MATH_REV_CORE_AUTODIFFSTACKSTORAGE_HPP` and `-DSTAN_MATH_REV_CORE_INIT_CHAINABLESTACK_HPP` into rstan's Makevars file, then I get compiler errors when building rstan like
```
In file included from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/chainable_alloc.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/vari.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/var.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/build_vari_array.hpp:5,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core.hpp:5,
                 from ./stan/model/model_base.hpp:5,
                 from Module.cpp:2:
/home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/chainablestack.hpp:12:24: error: ‘AutodiffStackSingleton’ does not name a type
 using ChainableStack = AutodiffStackSingleton<vari, chainable_alloc>;
                        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/vari.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/var.hpp:4,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/build_vari_array.hpp:5,
                 from /home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core.hpp:5,
                 from ./stan/model/model_base.hpp:5,
                 from Module.cpp:2:
/home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/chainable_alloc.hpp: In constructor ‘stan::math::chainable_alloc::chainable_alloc()’:
/home/ben/r-devel/library/StanHeaders/include/stan/math/rev/core/chainable_alloc.hpp:19:5: error: ‘ChainableStack’ has not been declared
     ChainableStack::instance_->var_alloc_stack_.push_back(this);
     ^~~~~~~~~~~~~~
```
etc.

**Comment by wds15** [comment]
I will try to look at things today again. Sounds like we are getting closer now.

**Comment by SteveBronder** [comment]
was this resolved?

**Comment by wds15** [comment]
The rstan issues were resolved a while ago.
