### ISSUE TITLE
range checks should throw `std::out_of_range`

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#193]
The errors thrown by all the `check_` functions that deal with index ranges should throw `std::out_of_range`

* [ ] code review
    * [ ] list functions that need to be fixed here

* [ ] push matching issue up to Stan to fix spec in manual

* [ ] push issue up to Stan or CmdStan to make sure the out-of-range exceptions really are fatal

**Comment by syclik** [comment]
These check functions throw `std::out_of_range` and I’ve updated the doc (where necessary):
- `stan/math/prim/mat/err/check_column_index.hpp`
- `stan/math/prim/mat/err/check_range.hpp`
- `stan/math/prim/mat/err/check_row_index.hpp`
- `stan/math/prim/mat/err/check_std_vector_index.hpp`

These additional files throw `std::out_of_range` and I’ve updated the doc (where necessary)
 :
- `stan/math/prim/mat/fun/get_base1.hpp`
- `stan/math/prim/mat/fun/get_base1_lhs.hpp`
- `stan/math/prim/mat/meta/VectorViewMvt.hpp`
- `stan/math/prim/scal/meta/container_view.hpp`

I changed this to throw `std::invalid_argument` since it seems more natural and I’ve updated the doc (just for this function… not the rest of the template specializations):
- `stan/math/prim/scal/meta/length_mvt.hpp`

I updated all the doc to the function calls that directly call the functions listed above.

**Comment by bob-carpenter** [comment]
Is this all fixed with #361?  I didn't see much code change there.  I'm not sure what manual you think needs to be updated---the Stan manual doesn't talk about specific exception types (at least I don't recall it doing so).

**Comment by syclik** [comment]
I think I wanted to add doc about Stan stopping once it hit one of these exceptions because unlike rejectiond, these indicate problems with sizing that should be resolved.

**Comment by bob-carpenter** [comment]
Does Stan currently stop at a range exception?
We did talk about that before and it makes sense.  Especially
if we can't get integer indexes out of parameters (without
loop hacking).

Are you suggesting each function in the Stan manual talk about
the kind of exceptions it throws?  The behavior in the face
of these exceptions would go in the algorithms section.

**Comment by syclik** [comment]
No. I currently treats it like a rejection. 

And I'm just suggesting we indicate that out of range  will stop sampling. Not that every function get doced.

**Comment by bob-carpenter** [comment]
But how will users know what throws out_of_range exceptions?
I wouldn't even know without looking at the source.

Exceptions per se aren't really part of the language from the
interface perspective, though they are if you look at the C++ level.

I'm not even sure what kind of exception our reject() statement
throws, but if we start distinguishing behavior, then we want to
specify that and probably allow rejection to be more fine-grained
to allow users to write proper function error handling.
