### ISSUE TITLE
Adding basic operations for symmetric matrices

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#196]
I am copying this over from [Stan issue #1647](https://github.com/stan-dev/stan/issues/1647) because I put the issue in the wrong place initially. Here's the original feature request:
## Feature Request

**Version**
2.8.0++

**Description**
Add functions to do addition, subtraction, element multiplication, and element division for symmetric matrix. Because these functions need to check if the matrices are symmetric, the check for whether a matrix is symmetric will be updated to be more efficient.

**Example**

```
//user has specified some symmetric matrix A and B
C <- sym_add(A, B);
```

**Additional Information**
What should these functions be called? I'm thinking sym_add and sym_substract for addition and subtraction and sym_elem_multiply and sym_elem_divide for multiplication and division respectively.

Also, what should the function calls be? The following seem to make sense:

For symmetric matrix A and B,

```
//Adds a symmetric matrix to itself
sym_add(A) 

//Adds a symmetric matrix to another symmetric matrix
sym_add(A, B)
```

**Comment by rayleigh** [comment]
From Bob:

What are the slashes for in the text? And you should quote the code.

Also, what is the plan to make the test for symmetry more efficient?

Finally, I'm not sure we even need to do the test for symmetry. It could be defined to take the lower-triangular portion, reflect to top and do the addition --- that's how Eigen works. Check out their expression templates to see how they do it.

**Comment by rayleigh** [comment]
From betanalpha:

I believe Eigen can also leverage the symmetry expression templates
when doing Cholesky decompositions.

**Comment by bob-carpenter** [comment]
This issue is trickier than this feature request makes out.

The first step we need is a precise definition of what the intended function is going to do, not just in terms of values, but in terms of `math::var` objects and the expression graph and how the chain rule's propagated.  

If we try to define `add_sym(A, B)`  by wrapping `A`and `B` in self-adjoint views, then there are a couple immediate problems.

1.  If we supply matrices with scalar type `math::var`, you'd wind up with a result where no derivative information is propagated to the upper or lower trianular portion of A or B, and I think you'd also get doubling of other derivatives because the below-diagonal elements get copied above the diagonal.

2.  If we naively try to add symmetric views in Eigen we run into the problem that Eigen doesn't support mixed operations.

I think (1) may be OK with a careful definition, but it's important to make sure whatever gets implemented here will do what people want it to do higher up (here, adding GP covariance functions efficiently, I think).

**Comment by syclik** [comment]
This is a much bigger issue. We don't have symmetric matrix types yet and if we do, it should be fixed with operator overloads (if we use a static type).
