### ISSUE TITLE
Replace second-order finite diffs with finite diffs of autodiff gradients for testing

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#2300]
## Description

We have second- and third-order autodiff functions defined in terms of finite differences.  This leads to poor accuracy for our tests.   An improvement would be to

* replace second-order finite difference Hessian definition with differences of autodiff gradients
* replace third-order finite difference tensor definition with differences of autodiff Hessians

As a side benefit, it'll be faster.

## Example

This is an implementation refactoring that should lead to higher accuracy.  It does not change the behavior of any functions other than to improve arithmetic accuracy.

## Expected Output

More precise output.

#### Current Version:
v3.4.0

**Comment by adamhaber** [comment]
I'll try to tackle this.

**Comment by adamhaber** [comment]
By the way, not sure how common this problem is, but when I tried following the hello world instructions and ran:
```
> make -j4 -f /path/to/stan-math/make/standalone math-libs
```
I got:
```
x86_64-apple-darwin13.4.0-ar: creating archive /Users/adamhaber/projects/stan_stuff/math/lib/sundials_5.6.1/lib/libsundials_nvecserial.a
/Users/adamhaber/miniconda3/bin/x86_64-apple-darwin13.4.0-ranlib: object: /Users/adamhaber/projects/stan_stuff/math/lib/sundials_5.6.1/lib/libsundials_nvecserial.a(nvector_serial.o) malformed object (unknown load command 1)
/Users/adamhaber/miniconda3/bin/x86_64-apple-darwin13.4.0-ar: internal ranlib command failed
make: *** [/Users/adamhaber/projects/stan_stuff/math/lib/sundials_5.6.1/lib/libsundials_nvecserial.a] Error 1
make: *** Waiting for unfinished jobs....
```
which, AFAICT, implies there was a mess between different clang/ar/ranlib installations on my laptop (might be related to [this]?(https://statmodeling.stat.columbia.edu/2019/12/11/macbook-pro-16-inch-2019-quick-review/)). 

What worked (eventually) was setting in `make/local`:
```
CXX=clang++
AR=llvm-ar
RANLIB=llvm-ranlib
```
is there some installation doc this can go into?

**Comment by adamhaber** [comment]
Concerning the issue itself - just to make sure I understand (it's my first interaction with the stan-math codebase):

For the following files:
- `finite_diff_hessian.hpp` and `finite_diff_hessian_auto.hpp`
- `finite_diff_grad_hessian.hpp` and `finite_diff_grad_hessian_auto.hpp`

1. The difference between `foo` and `foo_auto` is that the step size is given in the former, and automatically determined in the latter, right?
2. `finite_diff_hessian_auto` is used twice in `test_ad.hpp` - once in `test_hessian_fvar` and once in `test_hessian`. What is the difference between these two tests?
3. `finite_diff_grad_hessian_auto` is used once in `test_ad.hpp` - in `test_grad_hessian`. 

Also - it seems like `test_hessian`
> Tests that the specified function applied to the specified argument yields values, gradients, and Hessian consistent with finite differences

whereas `test_grad_hessian` 

> Tests that the specified function applied to the specified argument yields values, Hessian, and gradient of Hessian consistent with finite differences

Is this redundancy intentional, or do we want these functionalities to be combined somehow?

**Comment by bob-carpenter** [comment]
@adamhaber:

1.  There's probably no reason to not use the auto one.  So `lkj_corr_test` can probalby just be updated to use that.

2.  `test_hessian_fvar` tests the `fvar<fvar<double>>` (forward nested in forward) implementation of Hessians, whereas `test_hessian` tests the `fvar<var>` implementation (reverse nested in forward).  

3. Unlike `hessian()`, There's only one implementation of `grad_hessian()`.

3+.   `grad_hessian()` calculates the gradient of the Hessian, which is a 3D structure (aka a tensor in ML parlance) of 3rd derivatives.  `hessian()` only calculates the Hessian, a matrix of 2nd derivatives.    We only want to call `grad_hessian()` when absolutely necessary.    The same structure applies with Hessians and gradients.  Usually, computing the higher-order derivatives gives you the lower-order ones for free.

**Comment by adamhaber** [comment]
Thanks @bob-carpenter .

Just to make sure I'm not missing anything - the expected output is a rewrite of `finite_diff_[grad_]hessian_auto.cpp` such that 
> replace second-order finite difference Hessian definition with differences of autodiff gradients
replace third-order finite difference tensor definition with differences of autodiff Hessians

as well as deprecating the non `_auto` files?

> 3+. grad_hessian() calculates the gradient of the Hessian, which is a 3D structure (aka a tensor in ML parlance) of 3rd derivatives. hessian() only calculates the Hessian, a matrix of 2nd derivatives. We only want to call grad_hessian() when absolutely necessary. The same structure applies with Hessians and gradients. Usually, computing the higher-order derivatives gives you the lower-order ones for free.

So why not test gradients in `test_grad_hessian`, as well? Basically I'm trying to understand why one of them is focused on (very sloppily) 0th, 1st and 2nd orders and the other one on 0th, 2nd and 3rd.
