### ISSUE TITLE
Suspicious commit in master and release/v4.0.1

### ISSUE THREAD

**Issue by hsbadr** [stan-dev/math#2374]
fb220795ed1c1628c6ea5becee3423cc268a495c, in both `master` and `release/v4.0.1`, doesn't look good. I think it reverts much more that it supposed to do.

@serban-nicusor-catena @rok-cesnovar @bbbales2

**Comment by rok-cesnovar** [comment]
What particulary do you have in mind in terms of "reverts much more"?  Can you give an example?

**Comment by hsbadr** [comment]
> What particulary do you have in mind in terms of "reverts much more"? Can you give an example?

For example, do you really want to revert `lib/boost` update from `1.72.0` to `1.75.0` in `v4.0.1`?

Just wanted to bring it to your attention, but it's ok if all is intended.

**Comment by hsbadr** [comment]
At least, it should be revered with merging the patches in `master` into `develop`.

**Comment by hsbadr** [comment]
At least, it should be reverted with merging the patches in `master` into `develop`.

**Comment by hsbadr** [comment]
At least, it should be reverted with merging the patches from `master` into `develop`.

**Comment by rok-cesnovar** [comment]
> update from 1.72.0 to 1.75.0 in v4.0.1

No we do not want that. We accidentally merged develop to master and then reverted. Which is why all this mess. Develop has 1.75, master has 1.72.

Looking at https://github.com/stan-dev/math/tree/master/lib its 1.72.0 which is correct.
https://github.com/stan-dev/math/tree/release/v4.0.1/lib has 1.72.0 which is also correct

and develop https://github.com/stan-dev/math/tree/develop/lib has 1.75.0 which is also correct.

Thanks for looking into this, these things get tricky so more eyes is good.

We will merge the changes in master to develop as soon as we triple check everything is fine.

**Comment by hsbadr** [comment]
@rok-cesnovar Sounds good. Closing this issue!
