### ISSUE TITLE
function matrix_normal_prec_log: unit test, add doc, add to function signatures

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#24]
_From @syclik on October 9, 2013 18:25_
- [x] add unit tests
- [x] add documentation
- [ ] add unit tests for gradients

And then create an issue in stan-dev/stan to 
- [ ] add to `src/stan/gm/function_signatures.h`
- [ ] add model instantiation tests

_Copied from original issue: stan-dev/stan#271_

**Comment by syclik** [comment]
_From @mbrubake on January 30, 2014 22:16_

I don't believe this has been finished.  Can we leave it open until it gets done?  I've assigned it to a future milestone in the meantime.

**Comment by syclik** [comment]
@mbrubake, sorry about that... I didn't mean to close it. I must have hit the wrong button. I'll walk through all the issues I just touched to see if I accidentally closed any others.

**Comment by syclik** [comment]
_From @randommm on May 11, 2014 1:43_

Isn't this actually finished since in #305 the multivariate functions over matrix outcomes are requested to be removed from Stan? (I suppose a discussion on this has happened when I wasn't watching the stan-dev mailing list)

**Comment by syclik** [comment]
_From @mbrubake on May 11, 2014 15:31_

Not really.  This is a matrix normal distribution, ie, a distribution over
matrices.  #305 was referring to an unused variant of the multi normal
distribution which was an early effort at vectorizing.

**Comment by syclik** [comment]
#1344 is a duplicate of this one.

**Comment by sakrejda** [comment]
Looks like the function does have documentation, has tests, but I don't see it in [src/stan/lang/function_signatures.h](https://github.com/stan-dev/stan/blob/develop/src/stan/lang/function_signatures.h).  Exposing it should be a Stan language issue not a math issue.  @rtrangucci Am I right that this issue is complete? Do you want to keep it open?

**Comment by rtrangucci** [comment]
The only reason we haven't added it to the language is because we don't have explicit tests for the gradient calculations. I had a branch open a long ago where I was able to match finite diff gradients with autodiff gradients for all but one parameter. I'll need to dig that up and try to figure out if it was my finite diff code that was failing or the matrix_normal_prec_log's gradient calc that was failing

**Comment by sakrejda** [comment]
That's good to know as it makes this issue much more specific.  If you can dig up the branch, put it on the repo, and link it to this issue, it would make it easier for somebody else to pick up in case you don't get to it.

**Comment by syclik** [comment]
@rtrangucci, were you able to find that branch?

**Comment by randommm** [comment]
@rtrangucci hi, I'm interested in tackling this issue but since you are assigned to it, I better ask if you are not already currently working on this.

**Comment by bob-carpenter** [comment]
You might want to hold off a few days until the new operands and partials is merged.  It's going to change the way we do all these a bit (make it easier, especially for multivariates).

**Comment by rok-cesnovar** [comment]
In terms of Stan Math this issue was closed, I dont think it was ever added to the languages (at least I cant find a record in stan or stanc3). Please open a new issue there if you still want this implemented, the unit tests and docs are there so closing.
