### ISSUE TITLE
mingw error on devel because of too big of a file

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2408]
## Description

```
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: test/unit/math/mix/fun_30_test.o: section .pdata$_ZN4stan4test8internal12test_hessianIZZNS1_16expect_ad_helperIZN19lub_constrain_tests10expect_vecISt6vectorIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEESaIS9_EES9_SB_EEvRKT_RKT0_RKT1_EUlSE_SH_SK_E_ZNS1_13expect_ad_vvvISL_SB_S9_SB_EEvRKNS0_13ad_tolerancesESE_SH_SK_RKT2_EUlSE_E0_JSB_S9_SB_EEEvSP_SE_SH_RKNS8_IdLin1ELi1ELi0ELin1ELi1EEEDpT1_ENKUliE_clEiEUlSE_E_EEvSP_SE_SW_db: string table overflow at offset 10000302

C:\Users\Administrator\AppData\Local\Temp\ccXJOQze.s: Assembler messages:

C:\Users\Administrator\AppData\Local\Temp\ccXJOQze.s: Fatal error: can't close test/unit/math/mix/fun_30_test.o: file too big
```

Do we need to break up the tests more for mingw?

**Comment by rok-cesnovar** [comment]
> Do we need to break up the tests more for mingw?

No, this is due to jumbo tests that are used for RTools 4.0. We need to descrease jumbo size again for Windows, though I did that just a few days ago https://github.com/stan-dev/math/pull/2394 and am now inclined to just turn it off for windows.

No tests will pass right now as both machines that could run OpenCL are offline. @bgoodri will not be on premises for a while so I am guessing the only reasonable thing is to turn off OpenCL tests for awhile which is really really bad but at least wont halt other development. The Linux machine sometimes comes back up on its own but hasnt in the 16 hours now so that seems less and less possible now.

**Comment by SteveBronder** [comment]
Okay in the interlude @t4c1 if you want another machine to run the opencl tests lmk and I can run them on my gpu/cpu locally at least as a spot check
