### ISSUE TITLE
add `inv_Phi_log` which is `inv_Phi(log(x))`

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#2697]
@andrjohns has done some tests on `inv_Phi` and it's more stable to compute everything in terms of logs. He has a Stan implementation at https://github.com/andrjohns/brms/blob/feature/gaussian-copula/inst/chunks/fun_inv_Phi_log.stan. 

It is exactly the same algorithm as in stan-math but allows the user to input the value on the log scale. Doing all the interval calculations on this scale but still returning the same result as `inv_Phi`.

```r
> inv_Phi_log(log(0.3))
[1] -0.5244005
> qnorm(0.3)
[1] -0.5244005
```

**Comment by bob-carpenter** [comment]
It certainly gives you more range.  It's also the same result as `normal_lcdf(x | 0, 1)`, so it'd be good to improve `normal_lcdf` if there are algorithmic improvements here.

Can we call this `log_inv_Phi`, though, to match our other functions (e.g., `log_inv_logit`, `log_1m_inv_logit`, etc.)?

**Comment by andrjohns** [comment]
The naming is a bit tricky, since it's not quite the same as the other `log_` functions. `log_inv_Phi` implies that the function is `log(inv_Phi(x))`, but it's actually `inv_Phi(exp(x))`.

Also, I might be mistaken, but isn't this distinct from the `normal_lcdf` since `inv_Phi` is the quantile function of the standard normal, not the CDF?

**Comment by bob-carpenter** [comment]
Sorry, @andrjohns---if that's the behavior, then your name is correct and it's not synonymous with the normal log cdf.
