### ISSUE TITLE
Warning about ops_partials_edge struct declaration

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2755]
## Description

With the latest clang I am seeing this warning:
```
/Users/rok/.cmdstan/cmdstan-2.29.2/stan/lib/stan_math/stan/math/rev/functor/operands_and_partials.hpp:29:1: warning: 'ops_partials_edge' defined as a class template here but previously declared as a struct template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
class ops_partials_edge<double, var> {
^
/Users/rok/.cmdstan/cmdstan-2.29.2/stan/lib/stan_math/stan/math/prim/functor/operands_and_partials.hpp:21:1: note: did you mean class here?
struct ops_partials_edge;
^~~~~~
class
```

Is the struct required there? I am not sure.

#### Current Version:
v4.3.2

**Comment by wds15** [comment]
The message suggest to write `class ops_partial_edge` instead of the struct. That seems to make sense to do that as you then align declaration and forward declaration. That at least how it looks to me. structs are objects with a default public membership while classes are objects with a default private membership...but apart from that they are the same.
