### ISSUE TITLE
boost 1.82 upgrade

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2898]
## Description

Boost 1.82 is released and we should update to it.

#### Current Version:
v4.6.1

**Comment by wds15** [comment]
In the past we aligned boots with the CRAN r version of bh…which is 1.81 for now.

**Comment by wds15** [comment]
If you have a good reason to go to 1.82 ... then I'd be with you. Otherwise just go with 1.81 is what I would say. From interacting with the maintainer of BH I understood that he intends to do once per year updates only. This is due to the large effort of upgrading (such that my bet would be at 1.83 or even 1.84 to land on CRAN as BH). In any case, I do understand that rstan is so much behind such that it is almost hard to argue for compatibility with it. Given that you have already invested in an 1.82 PR maybe we should just go with it and simply discourage usage of 1.82 only features?

**Comment by SteveBronder** [comment]
> Given that you have already invested in an 1.82 PR

I just let your script run and made one fix so this was very low effort on my part

@wds15 @WardBrian the unordered flat map is in 1.81, but 1.82 has a major update to the unordered containers which says

> Fixed bug in internal emplace impl where stack-local types were not properly constructed using the allocator of the container which breaks uses-allocator construction.

Which feels very necessary for our use case (I need to unordered container in the reverse pass of the multi index assignment.)

(ctrl+f for 'Unordered' in the release notes below)
https://www.boost.org/users/history/version_1_82_0.html

Though tbh I'm fine with not having a flat unordered map for right now and just waiting while we do a 1.81 upgrade for now

**Comment by SteveBronder** [comment]
Actually I'm going to close this for now
