### ISSUE TITLE
create and expose if_else() function for integers

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#295]
#### Summary:
We need a function with this signature
`int if_else(int, int, int)`
This would be particularly useful for variable-sized declarations.

#### Description:
Currently,
`if_else(int, int, int)`
returns a real, which does not work as a declaration size

#### Reproducible Steps:
`matrix[N, K] X[if_else(just_one, 1, T)];`

#### Current Output:
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

dimension declaration requires expression denoting integer; found type=real
```

#### Expected Output:
None

#### Additional Information:
I'll do it

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
Mitzi may finish the ternary op this weekend which will do
this more efficiently than if_else for any conformable types,
so (int ? T1 : T2) will return promote_args<T1, T2>::type.
And it's a pure Stan solution --- there can't be a function
because that'll cause eager evaluation of the expressions.
  
- Bob

**Comment by bgoodri** [comment]
OK. Let's do that instead.
