### ISSUE TITLE
can we reorganize to put the constraint transforms into their own folder?

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#3027]
I'd like to add some additional constraint transforms and have these be referenced more easily. Is it a heavy lift to reorganize and have a folder dedicated to these?

**Comment by syclik** [comment]
I don't think it'd be that heavy of a lift. What do you propose?

**Comment by SteveBronder** [comment]
I like this idea. Constraints are certainly a "special" function for stan math like how we have a folder for probability distributions. I'd actually go further and propose we merge the `*_constrain` and `*_free` files for each constrain as well. Each constrain needs an associated free and I think it makes sense to have them all together in one file.

> What do you propose?

Just a `constraints` folder feels fine to me. For backwards compatibility should we leave the literal files there just empty? Otherwise code that includes those specific files would fail to compile

**Comment by SteveBronder** [comment]
> For backwards compatibility should we leave the literal files there just empty?

Or just an include to the `stan/math/*/constraints/this_constraint.hpp` file

**Comment by spinkney** [comment]
I can just never find what the constraint files that I'm looking for, this would make it much easier to navigate. I'm good with `constraints` as the folder name. 

> I like this idea. Constraints are certainly a "special" function for stan math like how we have a folder for probability distributions. I'd actually go further and propose we merge the `*_constrain` and `*_free` files for each constrain as well. Each constrain needs an associated free and I think it makes sense to have them all together in one file.

I agree that they can be merged together. That would make it much easier to read the constraint code.
