### ISSUE TITLE
Create basic lower-triangular matrix type

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/math#364]
#### Summary:

Introduce a basic matrix type that only stores the lower-triangular portion of a matrix

#### Description:

I'd like to specialize matrix operations for different types of matrices:

* lower triangular
* symmetric

This is mainly for multiplication, addition, Kronecker and Hadamard products. Eigen has specialized functions selfadjointView<Eigen::Lower>() and triangularView<Eigen::Lower>() that yield speed gains  compared to their non-specialized counterparts for multiplication, and addition.

Here is the design spec I had in mind:

```
template <typename T>
class lower_triangular {
  private:
    int rows_;
    int size_;

    inline int vech_ind(int i, int j, int N) {
      int ind = j * N + i - (j * (j + 1)) / 2;
      return ind;
    }
  public:
    Eigen::Matrix<T, -1, 1> vals_;

    lower_triangular(const Eigen::Matrix<T, -1, -1>& vals,
              const int rows)
      : rows_(rows), size_(rows_ * (rows_ + 1) / 2) {
        check_size_match("symmetric",
                         "Elements of ", "data", vars.size(),
                         "value ", "rows * (rows + 1) / 2", size_);
        vals_.resize(size_);
        for (int i = 0; i < size_; ++i) 
          vals_.coeffRef(i) = vals.coeffRef(i);
      }

    lower_triangular(const int rows)
      : rows_(rows), size_(rows_ * (rows_ + 1) / 2) {
        vals_.resize(size_);
      } 

    T& operator()(int i, int j) {
      check_less_or_equal("Indexer", "rows", j, i);
      int ind = vech_ind(i, j, rows_);
      check_less_or_equal("Indexer", "element", ind, size_);
      return vals_.coeffRef(ind);
    }

    int size() {
      return size_;
    }
    int rows() {
      return rows_;
    }
};
```

In order to expose this type to the Stan language we'll need to specialize the IO for lower-triangular matrices in `stan::io`.

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment]
We don't need implementation details in the design specs, but doxygen-like comments help.  For example, the constructor fills the matrix column major as in Eigen's default data layout.  You don't need `const` with `int` arguments in general, but you don't even need that int argument here as it can be calculated from the size of the `vars` argument.  Also, `size()` should just return the size of the stored `vars_`. 

What would help is if you say how this is going to get used.  As is, I don't see how you could use Eigen's triangular views with this class.  Do you just map the data and and self-adjoint view?  Then what do you use the `operator()` for?  

Also, is this intended to bo with a new type in the Stan language to complement the current basic types, int, real, vector, row_vector, and matrix?  Or do you want to add it to Eigen itself? 

If we wanted to add ito the Stan language, That'd be doable and it'd save some space, but lead to lots of updates everywhere in the language or redundancy.  For example, we'd want to make covariance matrices and correlation matrices symmetric, but that won't be backward compatible with everything we have in place now.

**Comment by rtrangucci** [comment]
Right. All of these ideas are informed by my recent experience recoding the multiply function.

As is, `multiply(Eigen::Matrix<var, -1, -1> A, Eigen::Matrix<var, -1, -1> B)` assumes that neither A nor B has special structure. However, if we had something like:

`multiply(stan::math::symmetric<var> A, Eigen::Matrix<var, -1, -1> B)`

we could pull the values into a lower-triangular matrix, and specialize the constructor's calculation of AB like so:

`Eigen::Matrix<double, -1, -1> AB = A.selfadjointView<Eigen::Lower>() * B`

and similarly the calculation of of the adjoints of A and B.  

The operator could be used to do element-wise updates (say by adding a constant to the diagonal). I would add this as a new type to the Stan language.

**Comment by bob-carpenter** [comment]
OK, that's what I was expecting.  With the current design sketch, that won't work because  `SelfAdjointView` on `A` because it's not a (template) method of `A`.  You'd have to pad the values and use a `Map`, I think, or perform a copy as part of the class.  So how about adding a method:

```
SelfAdjointView<T, Eigen::Lower> matrix_view() const;
```

on the class?   Or did you have something else in mind for getting that self-adjoint view?

P.S.  The arguments would be constant references.   Sorry to be so pedantic, but if any context calls for pedantry, it's spec writing.

P.P.S.  I don't think these things should be turned into issues until there's a concrete design spec that's ready to code.

**Comment by rtrangucci** [comment]
Yes, that's a great idea, I can add that to the spec. And yes, unfortunately I'm resigned to the fact that I'll need to make copies of the `double val_` . The code above was wrong; instead of:

`Eigen::Matrix<double, -1, -1> AB = A.selfadjointView<Eigen::Lower>() * B`

I should have written:

`Eigen::Matrix<double, -1, -1> AB = Ad_.selfadjointView<Eigen::Lower>() * Bd_`

where we've pulled out the vals_ from the varis like so:
```
MatrixXd Ad_(A.rows(), A.rows());
for (int j = 0; j < A.rows(); ++j)
  for (int i = j; i < A.rows(); ++i)
    Ad_(i, j) = A(i, j).val();

MatrixXd Bd_(A.rows(), B.cols());
for (int j = 0; j < A.rows(); ++j)
  for (int i = 0; i < B.cols(); ++i)
    Bd_(i, j) = B(i, j).val();
```

**Comment by bob-carpenter** [comment]
You wouldn't need to make copies if you stored the dense
matrix rather than just the array of values (you could use
dummy values for the above diagonal entries).  But then
it'd be more overhead to store.  If you only used it once,
it would be better to just store the values and copy on use.
At some point, it'll be more efficient to store the whole
dense matrix.

**Comment by rtrangucci** [comment]
I'm confused; at some point, we need to pull the doubles out of varis and
put them into an Eigen structure for computation of the function value and
the adjoints. The use case for this is as an input to a specialized matrix
vari that implements `chain()`.


Rob

**Comment by bob-carpenter** [comment]
That makes sense if you don't need to actually expose
a symmetric view of the entire matrix of type T.  This is why
I'm trying to clarify what the intended usage pattern is.

**Comment by bgoodri** [comment]
How do people feel about an antisymmetric matrix type?

**Comment by bob-carpenter** [comment]
Was that a joke?  Or does "antisymmetric" mean something other than not symmetric?  Also, let's keep the general discussion on our mailign lists and meetings and not sidetrack all these issues.

**Comment by bgoodri** [comment]
An antisymmetric matrix is one where A' = -A. It is the same issue as
symmetric or triangular in terms of how you want to store it, whether it
should be a base type, etc.

On Aug 24, 2016 7:02 AM, "Bob Carpenter" <notifications@github.com> wrote:

Was that a joke? Or does "antisymmetric" mean something other than not
symmetric? Also, let's keep the general discussion on our mailign lists and
meetings and not sidetrack all these issues.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stan-dev/math/issues/364#issuecomment-242027240>, or mute
the thread

**Comment by rtrangucci** [comment]
@bob-carpenter I talked to @syclik yesterday about whether any of the refactor would interfere with the work needed to pipe a new type through the language and he didn't think it would. I'd like to start working on it this weekend; do you have an idea of what changes I'd need to make to `src/stan/lang/generator.hpp` or `src/stan/lang/ast.hpp` to get a new matrix type working? Right now it seems like I'll need to:

* write a `lower_triangular_var_decl` similar to `cholesky_corr_var_decl`
* modify `write_array_vars_visgen` to handle `lower_triangular_var_decl`

I'm sure there's more, but I'm not sure where to go from here.

**Comment by rtrangucci** [comment]
I'm going to close this issue until we have a clear roadmap for this type. Further thinking is required.

**Comment by bgoodri** [comment]
What do we think of these new (?) nullary expressions to create a matrix (expression)
http://eigen.tuxfamily.org/dox/TopicCustomizing_NullaryExpr.html
for the purpose of implementing structured matrices?

**Comment by bob-carpenter** [comment]
That looks really promising.  It gives you the laziness you want
at the cost of a functor and a type helper struct.  Seems like it'd
be worth the price to me.  I can only imagine they kept those
separate because they reused some of the type helper structs. 

The only way it'll really speed things up is if we generalize all
of our matrix operations to take expression template arguments without
evaluating them.

Eigen makes my head hurt.

**Comment by bgoodri** [comment]
Well, with Eigen 3.3 we can mix scalar types,
http://eigen.tuxfamily.org/dox-devel/structEigen_1_1ScalarBinaryOpTraits.html
so maybe we want to go in the direction of rewriting the matrix operations.

**Comment by rtrangucci** [comment]
Wouldn't this also require rewriting our functions to take MatrixBase
rather than Matrix<T,R,C>?


Rob

**Comment by bob-carpenter** [comment]
We don't want to mix scalar types in Eigen if we 
don't have to---better to use double-only calls
and matrix derivatives wherever possible.

The only place the mixing may help is when we pass in a
`stan::math::var` argument to an Eigen operation (that'd be
one we don't have a matrix derivative for) and internally
a double matrix or vector or scalar gets created to operate
on the `stan::math::var` struct.  I don't know how often that
happens.

It might help with var + double situations if we haven't
overridden all those.
