### ISSUE TITLE
Put up wiki page for why we can't use MatrixBase everywhere

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#402]
#### Summary:
Doc why we can't use `MatrixBase` easily.

#### Description:
Put up a wiki page with a working example.

#### Additional Information:
Discussions exist on stan-dev.

#### Current Version:
v2.12.0

**Comment by bgoodri** [comment]
I am not aware of a thread on stan-dev that came to the conclusion that using `Eigen::MatrixBase` was technically difficult. It was all "this won't work" followed by "it works if you do it this other way" on repeat ...
https://groups.google.com/forum/#!searchin/stan-dev/MatrixBase%7Csort:date

**Comment by bob-carpenter** [comment]
I don't know of any remaining issues with using Eigen::MatrixBase, so
I think we can start using it in place of Eigen::Matrix in some general
argument locations.  I'm not sure if it lets us distinguish vectors from
row vectors from matrices, though.

The latest discussion sorted out the block() issues we were having
before.  It's hard to be confident that something works everywhere
because there's no test for that.

- Bob

**Comment by syclik** [comment]
@bgoodri, thanks! I completely forgot about the use of `coeff()`. I think that gets us past the hurdle. 

We should take inventory of what expression templates we can generate through `stanc` and make sure we understand how `MatrixBase` behaves on those.

**Comment by bob-carpenter** [comment]
This could also open up our ability to write our own template expressions, for efficient structured matrices.

**Comment by syclik** [comment]
I'm all for that.

**Comment by rtrangucci** [comment]
Yes, this'd be very good for our potential structured matrix operations:

https://eigen.tuxfamily.org/dox/TopicCustomizingEigen.html


Rob

**Comment by bob-carpenter** [comment]
Closing this as it's a non-issue.
