### ISSUE TITLE
standard normal distribution

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#430]
#### Summary:

Provide a `standard_normal` or `std_normal` or simply overload `normal` so that

```
y ~ standard_normal();
```

or

```
y ~ normal();
```

does the same thing as

```
y ~ normal(0, 1);
```

The advantage is that we could remove some needless arithmetic, which can wind up being done both for values and derivatives.

#### Current Version:
v2.12.0

**Comment by jgabry** [comment]
I like the idea of introducing a new one like `unit_normal` for this special behavior instead of changing `normal` to default to `normal(0,1)` if no arguments are provided. That way `normal` continues to behave exactly the same as the rest of our probability distributions. Regarding the name for the special distribution, maybe `standard_normal`? Is "unit normal" a common way to refer to `normal(0,1)` in some fields? In statistics publications and software I don't think I've ever seen "unit normal" instead of  "standard normal" but I don't know what's common in computer science and other fields.

**Comment by bob-carpenter** [comment]
"standard normal" does seem to be the usual term.  Don't know where I got "unit normal".

**Comment by rayleigh** [comment]
I've been working on this because I'm curious about how probability distributions are tested and I might want to do some work on issue #493. I've written the code and the test function, but not all tests are passing and I'm still trying to figure out why.

**Comment by andrjohns** [comment]
Closed via #609
