### ISSUE TITLE
refactor sequence views

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#464]
#### Summary:

We should refactor sequence views (VectorView, VectorViewMvt).

#### Description:

The current names and functionality are too hard to understand (and slightly buggy).

#### Current Version:
v2.13.0

**Comment by seantalts** [comment]
I'm going to try to summarize the current state and what's left to do for this:

It seems like VectorView and VectorViewMvt can be summed up with three use cases:
1. Input is either a scalar or a sequence of scalars and we'd like to use it as a sequence. This is now scalar_seq_view as of https://github.com/stan-dev/math/pull/486. After that pull request I'll still need to replace a few more uses (in prim/scal/err), but will do that in a separate pull since they're not of the same exact form as the probability distribution use cases.
1. Input is either some type of eigen vector or a `std::vector` of eigen vectors. This is what all the multivariate distributions use. Currently covered by VectorViewMvt, I propose to replace with vector_seq_view perhaps?
1. Whatever OperandsAndPartials is doing that I haven't quite figured out but [has a thread here](http://discourse.mc-stan.org/t/scalar-vector-and-matrix-views/174/11). I am ignoring this for now.

I'm gonna go forward on the vector_seq_view I think, and hopefully we can iron out what OperandsAndPartials needs maybe in a separate ticket and/or the discourse discussion?

**Comment by bob-carpenter** [comment]
Yes, the first point is why I wanted to just do the immutable sequence view first. 

Then (2) should look just like (1), only for vectors. It's then possible we'll be able to combine the code.  That's what I was talking about when I said I'd like to write them both then see if we can combine and that sometimes it's simpler to leave the apparently duplicated but utterly transparent code than to include subtle conditional behavior on template parameters.

We use some views that are writable and some that are known to be size zero and throw errors if accessed inside of OperandsAndPartials.  We can sit down and work through that together and see if we're going to have to modify existing classes or create new ones. Then we can get rid of all the old classes.

- Bob

**Comment by mcol** [comment]
VectorView and VectorViewMvt don't exist anymore.
