### ISSUE TITLE
matrix power operator

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#47]
_From @bob-carpenter on October 9, 2014 17:13_

Extend the power operator (`^`) to signature `(matrix,int):matrix`, with definitions
- `A^0 = I`
- `A^n = A^(n-1) * A`  for `n > 0`

Throw an exception if `A` is not square or if `n` is not positive.

This should be easy to build.  Extra credit if there's something clever that can be done for the gradients of each `A^n[i,j]` with respect to each `A[i',j']`.  Just storing the gradients is going to be order `K^4` for a `K` by `K` matrix.

_Copied from original issue: stan-dev/stan#1073_

**Comment by thelseraphim** [comment]
Two observations.

If we only want the matrix power it is much better to say:

- `A^0 = I`
- `A^1 = A`
- `A^2n = (A^n)^2`
- `A^(2n+1) = (A^n)^2 * A`

This greatly reduces the number of matrix multiplications.

If we actually want the derivatives, the thing to do is take the derivative at $t = 0$ of the expression $(A + tX)^n$ for various matrices $X,$ which is seen to yield

`XA^(n-1) + A X A^(n-2) + A^2 X A^(n-3) + ... + A^(n-1) X`

If $X$ and $A$ commuted this would just be $n A^(n-1) X$ as we expect from ordinary calculus, but generally this will not happen.

The case where $X$ is a matrix which is a single $1$ and otherwise zero recovers the derivative with respect to a single component of $A.$  In this case the products simplify greatly and are seen to just be picking out elements of various powers of $A$ and multiplying them together. So all that needs to be stored is $A, ..., A^(n-1)$ for a storage cost of $(n-1)K^2.$ Is this a thing we want to do?

**Comment by bob-carpenter** [comment]
Absolutely on both counts.  I didn't realize the derivative would work out so neatly, but that's where we'll get the big savings in memory and time.

The idea can be extended down to numbers other than powers of two using a binary representation.  If we save all the pieces as we double, we can reuse even more efficiently.  That is, we save `A^2`, `A^4`, `A^8`, as we build up by doubling then we have something like `A^12 = A^8 * A^4`.  So you build up to `floor(log2(n))` and then put the pieces back together via the binary coding.  Looks like it'd be fun to code.

The derivative trick looks great, and by all means this is the kind of thing we would want to do.

**Comment by bob-carpenter** [comment]
Oh, and I have an application for approximating steady-state of an HMM transition matrix to use as an initial distribution.  Or is there a way to do that the right way with `matrix_exp`?
