### ISSUE TITLE
VectorViewMvt of std::vector of Matrices always returns first Matrix

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#473]
#### Summary:
If you create a `VectorViewMvt` around a `std::vector` of Eigen vectors or matrices, when you index into the resulting view you always get back the first item in the `std::vector` even though it would appear you should get back the correct index (and throw an exception of out of bounds of the `std::vector`). 

#### Description:
There's a separate ticket out to completely revamp `VectorViewMvt` et al. This is to keep track of an existing bug. The `is_array` type parameter is set seemingly incorrectly based on the matrix type instead of on the `std::vector` type, resulting in the behavior above.

#### Current Version:
v2.14.0

**Comment by mcol** [comment]
As of #494, `VectorViewMvt` has been replaced by `vector_seq_view`. By design it's now not possible to instantiate a `vector_seq_view` of a matrix. As for creating a `vector_seq_view` around a `std::vector<VectorXd>`, the indexing works correctly (see `test/unit/math/prim/meta/vector_seq_view_test.cpp`).

Potentially, the only thing that this issue raises is the bound checking: currently `vector_seq_view` segfaults if used to access an index beyond the bounds of the container, but that's perhaps for a different issue.

Given all that, I don't see any reason to keep this open.
