### ISSUE TITLE
thread local option in C++11 for autodiff memory

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#551]
#### Summary:

Enable each thread to run its own autodiff for multi-threaded model log density and gradient evaluation.  

#### Description

C++11 now has a thread local option, which we can use to allow models to be used in a multi-threaded environment (one model per thread, that is).  

We want to do this in a way so that they are ifdef-ed out when not in use as there's a performance overhead (which should be measured).

This is related to https://github.com/stan-dev/stan/pull/2306

#### Current Version:
v2.15.0

**Comment by ariddell** [comment]
This is a blocker for PyStan 3 (stan-dev/httpstan#21).

**Comment by wds15** [comment]
How about I pull out of the branch `proto-threads-cxx11` the relevant parts which implement the thread safe AD stack in order to address this issue with a pull request?

What would be missing to do is to formulate a good test for this. My suggestion is to calculate the gradient of a function in multiple threads (using the `stan::math::gradient` for example) and then compare that the results from the different threads do match exactly. Do others have any other idea or suggestion as to what to test?

**Comment by bob-carpenter** [comment]
Nope---that's the only thing that matters, so that's what we should test.  We should engineer a test to make race conditions as likely as possible.  Is that lots of threads with very short runs?

**Comment by wds15** [comment]
Ok. A pull is up. It looks like we will need to still sort out compiler stuff. On my macOS I was able to run with

- Apple's clang++, 9.1.0 (clang-902.0.39.1)
- clang++ 5.0.0
- clang++ 6.0.0
- g++ 6.4.0

I have added a threaded gradient evaluation as test case.

**Comment by ariddell** [comment]
Closed by #809.
