### ISSUE TITLE
STAN AutoDiff runs slower and slower.

### ISSUE THREAD

**Issue by patwangx** [stan-dev/math#558]
#### Summary:

The same code runs slower and slower.

#### Description:

I wrote a piece of code to test the AutoDiff of STAN Math Lib.
The code are run in a loop for 1000 times.
The computing time for each loop increases.

#### Reproducible Steps:
```C++
#include <cmath>
#include <stan/math.hpp>
#include <vector>

int main() {
       clock_t start,end ; 
       for (int i=0;i<1000;i++)
       {
	start=clock() ;        
	stan::math::var mu = 0.5, sigma = 1.2;
	stan::math::var lp = 0;
	lp = mu*sigma ; 
	
	std::vector<stan::math::var> theta;
	theta.push_back(mu);
	theta.push_back(sigma);
	std::vector<double> g;
	 
     // stan::math::set_zero_all_adjoints();
	lp.grad(theta, g);
	end=clock() ;
	std::cout<<1.0e5*(end-start)/CLOCKS_PER_SEC<<std::endl;	
       }
	return 0;
}
```
#### Current Output:

Times for first ten loops:
1.5
0.2
0.1
0.2
0.2
0.1
0.1
0.1
0.7
0.2
And for last ten loops:
5.2
5.3
5.3
5.6
5.3
5.3
5.3
5.4
5.3
5.3

There is  a significant difference.  Much more slower at the end than at the beginning.

**Comment by bob-carpenter** [comment]
You are missing a `recover_memory()` call after `grad()`.  To see how the memory works and how to call our autodiff, see one of

* the arXiv paper:  https://arxiv.org/abs/1509.07164

* the implementation of gradients in `stan/math/rev/mat/functor/gradient.hpp`

In fact, we recommend users stick to our functions wherever possible because all the memory and autodiff types are encapsulated.

Given that this isn't a bug, I'm closing the issue.
