### ISSUE TITLE
hessian.hpp O(N^2)

### ISSUE THREAD

**Issue by stumarcus576** [stan-dev/math#570]
#### Summary:
At the top of C:\msys64\home\stuma\math-develop\stan\math\mix\mat\functor\hessian.hpp, it says the Hessian is computed in O(N^2) time. I had thought that forward-over-reverse AD could construct the Hessian in O(N) time. Is there a Hessian implementation in Stan Math which is O(N)?

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
The Hessian can't be O(N) because the output is size N^2.

The algorithm does N reverse-mode nested in forward-mode passes, one for each argument position `n in 1:N`.  In each of those `N` passes, you get a derivative `d/d.x[n] f(x)` out of forward mode using reverse-mode scalars, then you run reverse mode from there to get `d/dx[n] d/dx[i] f(x)` for all `i in 1:N`---essentially a row of the Hessian (or a column---I can never keep the ordering straight). 

This is more a question than an issue, so I'm closing it.
