### ISSUE TITLE
deprecate old GP covariance function names

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#756]
#### Summary:
"Rename" the old GP covariance function names, such as `cov_exp_quad`, and change to the new naming convention: `gp_exp_quad_cov`. 

#### Description:
GP covariance functions from now on will follow the same naming convention. I will:

1) rename the old functions to `gp_[name]_cov.hpp`, replacing all old function names with the new ones.
2) write the deprecated function names as wrappers, so we don't lose backward compatibility. 

After this update, when we remove old names in 3.0, we can remove the files without problems. 

An example of a wrapper in `prim` is:

```
template <typename T_x, typename T_sigma, typename T_l>
inline
    typename Eigen::Matrix<typename stan::return_type<T_x, T_sigma, T_l>::type,
                           Eigen::Dynamic, Eigen::Dynamic>
    cov_exp_quad(const std::vector<T_x>& x, const T_sigma& sigma,
                 const T_l& length_scale) {
  return gp_exp_quad_cov(x, sigma, length_scale);
}
```

**To change:**
`cov_exp_quad.hpp` 
`multi_gp_cholesky_log.hpp` 
`multi_gp_cholesky_lpdf.hpp`
`multi_gp_log.hpp`
`multi_gp_lpdf.hpp` 

#### Current Version:
v2.17.0

**Comment by drezap** [comment]
Hi - is there a reason no one has responded to this? I would really like to get this done, and add another covariance function this week. @syclik

**Comment by syclik** [comment]
sorry -- didn't realize this issue was waiting for a response (there wasn't a question or even an obvious response to make).

For what it's worth, what you wrote makes sense. If you're putting together the PR, I'd request the deprecated function has doxygen doc that says it's deprecated. For example:
https://github.com/stan-dev/math/blob/c36cfa2becfcc2a0673addb1600e9133e822998d/stan/math/prim/scal/prob/normal_log.hpp#L38
```
/**
 * @deprecated use <code>normal_lpdf</code>
 */
```

**Comment by drezap** [comment]
Hi - I've updated the issue with a list of all GP names that need be deprecated. Can someone please let me know if this list is exhaustive? Thanks!
