### ISSUE TITLE
refactor cvodes ode system

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#760]
#### Summary:
Refactor cvodes ode system to use `coupled_ode_system` facility.

#### Description:
The goal is to abandon two systems which actually do the same thing by now. This refactor routes execution of the cvodes solver through the `coupled_ode_system` facility. This will make it easier to add a possibly varying initial time later.

#### Reproducible Steps:
NA

#### Current Output:
NA

#### Expected Output:
NA

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
@wds15, if there are any more notes on design, would you please put them here?

Do any of the interfaces change? (even at the C++ level?)

**Comment by wds15** [comment]
I have put those notes into the pull or are u looking for other information?

Nothing changes in terms of how the `integrate*` functions are used. We just get rid of a lot of code. The pull net removes ~750 lines of code.

**Comment by syclik** [comment]
Sorry -- didn't get to the PR yet. I expected to find the design discussion with the issue, not the PR.

**Comment by syclik** [comment]
@wds15, I just took a quick look. I'll need more time. Things that would help:
- describe what's being refactored. I'm just blindly walking through the diff to understand the extent of the code change. It would seriously help if you told us what you've removed and what you've replaced it (in words instead of just relying on the code diff).
- was there anything you needed to do to make the different things line up in code? I figure that's where the most time needs to be spent in reviewing the code.

Otherwise, cool. It's great pulling out redundant code!

**Comment by wds15** [comment]
Will do the high-level description of whats happened into the pull. Fine with that?

BTW, we also gain ~20% in speed on my little example I tried.

**Comment by syclik** [comment]
Yup. It just needs to go somewhere. (Preferred on the issue before the PR gets started on, but being somewhere is better than no where.)

How do you determine the ~20% increase in speed? Can we include that test in the PR?

**Comment by syclik** [comment]
Or at least describe it so we can use it in the future.

**Comment by wds15** [comment]
The speed difference is described in the pull. What extra information would you need for that? Do you need as much detail so you would be able to run that performance test yourself?

**Comment by syclik** [comment]
Yes! We don't just need words, we need code! And some way to determine
whether we're slowing down or speeding up.

**Comment by wds15** [comment]
Hmm... I always run my performance tests on the side to ensure I do not mess up things. Can we treat that speed bump as an FYI for this pull? I am happy to put a bit more detail as to what I am doing there exactly... but we do have a lacking performance benchmark framework right now.

**Comment by syclik** [comment]
Yes. We don't have a general framework for it, so it won't be part of it,
but if you're claiming it, someone should verify it independently, no?

**Comment by wds15** [comment]
I don't think it needs to be confirmed by the reviewer, no. That's why I suggest to treat it as an FYI. Otherwise I suggest to remove this statement.

**Comment by syclik** [comment]
If you know that there is a performance difference, then before merging, it
should be verified by the reviewer. Or you should show it somehow. I really
don't think it's ok to let it slide in either direction. (slower or faster)

**Comment by wds15** [comment]
Enabling another reviewer to run the performance test himself would be asking for a lot. How about I file the log file of the run?

**Comment by bob-carpenter** [comment]
From @syclik:

<blockquote>
If you know that there is a performance difference, then before merging, it should be verified by the reviewer.
</blockquote>

For example, that `mdivide_right` pull request is now going to need a performance review if we follow this review policy, because we know it changes performance as it completely changes the way copying gets carried out.  

But I don't think the developer's knowing about performance changes matters.  It seems even more important for the reviewer to test speed if the developer has no knowledge of the performance impact of their changes.

The inevitable conclusion is that every pull request needs a performance regressiont test run in the past state and current state of code.  

That's putting a very high, ad hoc burden on each pull request and each review given our lack of general testing framework. 

Why single this pull request out for a performance audit?  My main concern here is that we be fair on pull requests in the sense of applying the same policies to all of them.

This general discussion should probably go on the forums, but it's direclty relevant for the changes requested on this pull request.

**Comment by syclik** [comment]
Let's move the general discussion to the forums. Wasn't trying to be
arbitrary. There is some method to the madness.

For this particular pull request:
- calling something a "refactor" and that leading to a 20% speed increase
is shocking; it smells off (am I the only one that thinks so?)
- given that @wds15 has now claimed that it does without explaining how or
why, I believe it, but I think it should be verified
- I'm just going on what's in the PR. If the PR clearly stated what's being
changed, why, and how we're getting a speed bump, it's a lot easier to
review knowing that's happening. Instead, the PR said it's a refactor, that
the main effect was reducing the size of the code base. As a side effect,
it reduces speed 20%. I flipped through the code and it wasn't obvious
where the speed was coming from.
- I'm just reviewing it with two things in mind: 1) verify that the code
does what is claimed in the PR and 2) make sure there isn't additional
risk. Since there isn't much to go on in the way of description, I'm going
to look at verifying the side effects. The other thing I could have done is
to ask @wds15 to provide more material to guide me through it. It could go
either way; I tend to err on the side of putting more work on me before
putting more work on others.

**Comment by wds15** [comment]
Just to clarify: I did not expect a speed bump. It is a bit of a surprise to me as well, but I take it. My hunch is that less copying is taking place and memory locality is improved. So the old version wrote Jy and Jtheta (Jacobian wrt to states and parameters) in dedicated Eigen matrices and then assembled the coupled system on the basis of matrix vector products. The `coupled_ode_system` on the other hand calculates the respective derivatives and as these are calculated things are immediately written into the coupled system. The `coupled_ode_system` is less readable to a human as I find, but apparently better to speed up for the compiler. Like I said, I haven't expected this speed increase nor have I intended one (but I take it). The main intent is to merge the two ode systems into a single one; after all the calculate they same stuff.
