### ISSUE TITLE
ode_system ctor takes theta by value instead of reference

### ISSUE THREAD

**Issue by ChrisChiasson** [stan-dev/math#775]
#### Summary:
The constructor for ode_system takes the theta parameter vector by value instead of by reference

#### Description:
Taking it by value can create extra copies of the values in the vector

#### Reproducible Steps:
Not applicable

#### Current Output:
Not applicable

#### Expected Output:
Not applicable

#### Additional Information:
If you want I can submit a pull request in the same way as issue #773.

#### Current Version:
v2.17.0

**Comment by wds15** [comment]
this is on purpose, because of line 61 in cvodes_ode_data.hpp. There we call the constructor with a temporary object whenever theta is varying. This forces us to take in the parameters by value as otherwise you run into trouble.

... and on a different note we are currently refactoring the cvodes system so that the ode_system is possibly gone soon (depending on how the current pull goes)...

So unless you also have a good suggestion for the problem I mention above, could you please close the issue if you come to the same conclusion that things are fine? Thanks!

**Comment by ChrisChiasson** [comment]
Disagree respectfully, due to automatic temporary object lifetime extension in C++. Temporary will be persisted until ctor exits.

**Comment by wds15** [comment]
Is that new? I remember seeing segfaults whenever I had by reference instead of by value. This is 1-2 years ago. So since when does this work? C++11?

**Comment by ChrisChiasson** [comment]
As far as I know, it is extremely old. Simple stuff like functions that take a string by reference would not be able to work with string literals (which then get coerced into std::string temporaries) without it.

**Comment by wds15** [comment]
So we could pass by reference, but store a copy of theta?

**Comment by ChrisChiasson** [comment]
Indeed, it should work.

**Comment by ChrisChiasson** [comment]
I was reading issue #760 and it seems like the class this issue is about will be removed, so I am going to close this issue (if possible).
