### ISSUE TITLE
Add alternative inv_logit parameterization to prevent underflow

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#874]
#### Summary:
Current implementation of ```inv_logit``` will underflow with large negative numbers, need to add alternative parameterization to prevent this.

#### Description:
Inverse logit currently implemented as:
```
inline double inv_logit(double a) {
  using std::exp;
  return 1.0 / (1.0 + exp(-a));
}
```

Which will underflow when ```a``` is large and negative. Can be addressed with an if statement (as is done in ```log_inv_logit```:
```
inline double inv_logit(double a) {
  using std::exp;
  if (a < 0.0)
    return exp(a) / (1.0 + exp(a));
  return 1.0 / (1.0 + exp(-a));
}
```

#### Current Version:
v2.18.0

**Comment by bob-carpenter** [comment]
Cool!  This took me a while to wrap my head around, but it was worth it.

* Expensive subcomputations like `exp(a)` should only be done once.  

* Make sure that reverse and forward mode autodiff call the `double` version

Also, if `a` is large magnitude and negative, `1 + exp(a)` will also round to `1`, so that only `exp(a)` is needed.  Which raises two points:

* is there  a better Taylor expansion around zero we could use?

* are the derivatives stable?



Which brings up the issue of whether there's a better Taylor series expansion.  I'd have to do too much math homework to figure that out, but maybe someone will know.  We should be able to get good precision around zero with the right expansion as there's a lot of representational latitude there (the smallest number greater than 0 is roughly 1e-300 whereas the smallest less than 1 is around 1 - 1e-16 or so).  

The `0.0` and `1.0` can just be `0` and `1`.  The `exp()` returns a double and will cause everything else to be automatically promoted (at compile time).

**Comment by andrjohns** [comment]
> - Also, if a is large magnitude and negative, 1 + exp(a) will also round to 1, so that only exp(a) is needed

That's a good point! What we could do is define a constant: ```LOG_EPSILON = log(EPSILON)``` and then add a(nother) conditional so that we don't bother with the denominator if it's going to round down to 1:
```
if (a < LOG_EPSILON)    \\implies exp(a) < EPSILON
  return exp(a)
```
> - Are the derivatives stable in the given formulation?

We don't need to worry as much about the derivatives. The derivative for the inverse logit is:
```
d/da inv_logit(a) = inv_logit(a)*(1-inv_logit(a))
```
So as long as the function itself can handle extreme values, the derivative won't be a problem
