### ISSUE TITLE
Beta Binomial CDF gives non-monotone results

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#912]
#### Summary:
CDF functions should always return monotone output with increasing input value. The BetaBinomial CDF does violate this.

#### Description:
See Stan program below which fails under cmdstan 2.17.1 and develop (as of 22nd June 18).

#### Reproducible Steps:

```stan
parameters {
  real<lower=0,upper=1> dummy;
}
generated quantities {
  real m = log(100);
  real s= log(100);
  real a = lognormal_rng(m, s);
  real b = lognormal_rng(m, s);
  int N = poisson_log_rng(normal_rng(m, s));
  
  for(n in 0:(N-1)) {
    real cdfn = beta_binomial_lcdf(n| N, a, b);
    real cdfn1 = beta_binomial_lcdf(n+1| N, a, b);
    if(cdfn1 < cdfn) {
      print("n = ", n);
      print("N = ", N);
      print("a = ", a);
      print("b = ", b);
      reject("Investigate me please!");
    }
  }
}
```

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
This should be tackled at the same time as #688

**Comment by mcol** [comment]
The problem here seems to be more complex than the one in #688. I don't fully understand it yet, but running @wds15's model led me to a set values that demonstrate the problem, and after exposing the beta-binomial lcdf function in R via rstan, I got the following:
```
> betabinomial(2, 10, 148036, 1.98592)
[1] -21.62329
> betabinomial(3, 10, 148036, 1.98592)
[1] NaN
```

With respect to these lines: https://github.com/stan-dev/math/blob/490c18d18d349a27dc782bf80e059ca1f11fc524/stan/math/prim/scal/prob/beta_binomial_lcdf.hpp#L105:L107, the `NaN` case happens because `C = 1.0000000000204339` so that `Pi = -0.0000000000204339`, and taking the log fails.

My current feeling is that there is some loss of precision somewhere, and `C` goes above 1 when it should have stayed strictly below that (at least the code assumes that).

**Comment by nhuurre** [comment]
The `_lccdf` computation is identical to `_lcdf` except that `Pi = C` instead of `Pi = 1-C`.
`C` is just the value of the CCDF so it definitely should not exceed 1. Given that it does, CCDF is also broken.
I don't know where the loss of precision comes from. The values don't look too big for Beta or Gamma functions to break. Maybe the problem is F32.
It's weird is how the calculation starts on the log scale but then it switches to linear scale halfway through. Surely it's better to do everything on the log scale. And writing out the `lgamma`s is no better than `lbeta`. So the formula should be
```
lccdf(k|N,a,b) =
  log(F32(1, a+k+1, -N+k+1, k+2, -b-N+k+2, 1))
  + lbeta(b+N-k-1,a+k+1)
  - lbeta(a,b)
  - lbeta(N-k,k+2)
  - log(N+1)
```

The derivatives aren't quite optimal either. There's
```cpp
double Pi = C;
...
double g = -C * (...);
edge1_.partials_[i] -= g / Pi;
```
which clearly can be simplified.

Once CCDF has been fixed, CDF can be obtained from the symmetry
```
CDF(k|N,a,b) == CCDF(N-k-1|N,b,a)
```
