### ISSUE TITLE
Make return_type, partials_return_type, include_summands use variadic template parameters

### ISSUE THREAD

**Issue by dpsimpson** [stan-dev/math#977]
## Description
A number of commonly used template meta-programs have a fixed number of template parameters. This can be fixed using variadic templates.

The specific metaprograms that I've noticed are;
- `return_type` (max 6 types)
- `partials_return_type` (max 6 types)
- `include_summands` (max 10 types)
## Example

None

## Expected Output

The function should work exactly as before, including promoting types with lower precedence than `double` to `double`

## Additional Information
Only `return_type` has a unit test

## Current Math Version
v2.18.0

**Comment by syclik** [comment]
Thank you! Thanks for:
1. writing a clear issue that is scoped well enough for any dev to read, understand, and possibly implement against.
2. working on improving existing code'.

We wrote all of this pre C++11, so we couldn't use variadic templates. We can now and it's going to be a lot easier to code. If you see any other parts of our code that could benefit from something like this, please file an issue. If filing an issue is too much effort (because this is clean and that does take effort), just pop it on discourse and I can take care of formulating the issue.
